<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Documentação Técnica: MM_2026_novos_cadastros – Multimorbidade</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./script_MM.html" rel="next">
<link href="./pente_fino_HAS.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-cf0de2a877c7d4b42ae21f6d8e35c82d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-d79f8217e01dd2a5306137134a907536.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-cf0de2a877c7d4b42ae21f6d8e35c82d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./docu_enxuto.html">Documentação Técnica: MM_2026_novos_cadastros</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Multimorbidade</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apresentação</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./etapas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Etapas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CIDs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CIDs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./HAS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hipertensão arterial</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diabetes Mellitus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Síndromes Coronarianas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ICC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Insuficiência Cardíaca</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IRC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Doença renal crônica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multimorbidade</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PoliF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Polifarmácia</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fragil.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fragilidade em idosos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lacunas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lacunas de cuidado</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pilula_CI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pílulas Síndrome Coronariana Crônica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pilulas_IC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pílulas para Insuficiência Cardíaca</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./implementacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Implementação</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rastreios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rastreios neoplasias</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pente_fino_DM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pente Fino Diabetes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pente_fino_HAS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pente Fino HAS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./docu_enxuto.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Documentação Técnica: MM_2026_novos_cadastros</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./script_MM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tabela MM_2026_novos_cadastros_stopp_start</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#visão-geral" id="toc-visão-geral" class="nav-link active" data-scroll-target="#visão-geral">Visão Geral</a>
  <ul class="collapse">
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link" data-scroll-target="#objetivo">Objetivo</a></li>
  <li><a href="#localização" id="toc-localização" class="nav-link" data-scroll-target="#localização">Localização</a></li>
  <li><a href="#granularidade" id="toc-granularidade" class="nav-link" data-scroll-target="#granularidade">Granularidade</a></li>
  <li><a href="#tabelas-dependentes-rodar-antes" id="toc-tabelas-dependentes-rodar-antes" class="nav-link" data-scroll-target="#tabelas-dependentes-rodar-antes">Tabelas Dependentes (rodar antes)</a></li>
  </ul></li>
  <li><a href="#arquitetura-de-dados" id="toc-arquitetura-de-dados" class="nav-link" data-scroll-target="#arquitetura-de-dados">Arquitetura de Dados</a>
  <ul class="collapse">
  <li><a href="#fontes-de-origem" id="toc-fontes-de-origem" class="nav-link" data-scroll-target="#fontes-de-origem">Fontes de Origem</a></li>
  <li><a href="#fluxo-das-ctes" id="toc-fluxo-das-ctes" class="nav-link" data-scroll-target="#fluxo-das-ctes">Fluxo das CTEs</a></li>
  </ul></li>
  <li><a href="#detalhamento-por-seção" id="toc-detalhamento-por-seção" class="nav-link" data-scroll-target="#detalhamento-por-seção">Detalhamento por Seção</a>
  <ul class="collapse">
  <li><a href="#seção-1-identificação-de-hivaids" id="toc-seção-1-identificação-de-hivaids" class="nav-link" data-scroll-target="#seção-1-identificação-de-hivaids">Seção 1 — Identificação de HIV/AIDS</a></li>
  <li><a href="#seção-2-exames-laboratoriais" id="toc-seção-2-exames-laboratoriais" class="nav-link" data-scroll-target="#seção-2-exames-laboratoriais">Seção 2 — Exames Laboratoriais</a></li>
  <li><a href="#seção-3-dados-demográficos-e-de-cadastro" id="toc-seção-3-dados-demográficos-e-de-cadastro" class="nav-link" data-scroll-target="#seção-3-dados-demográficos-e-de-cadastro">Seção 3 — Dados Demográficos e de Cadastro</a></li>
  <li><a href="#seção-4-medidas-antropométricas" id="toc-seção-4-medidas-antropométricas" class="nav-link" data-scroll-target="#seção-4-medidas-antropométricas">Seção 4 — Medidas Antropométricas</a></li>
  <li><a href="#seção-5-morbidades-por-cid" id="toc-seção-5-morbidades-por-cid" class="nav-link" data-scroll-target="#seção-5-morbidades-por-cid">Seção 5 — Morbidades por CID</a></li>
  <li><a href="#seção-5b-critérios-expandidos-de-has" id="toc-seção-5b-critérios-expandidos-de-has" class="nav-link" data-scroll-target="#seção-5b-critérios-expandidos-de-has">Seção 5B — Critérios Expandidos de HAS</a></li>
  <li><a href="#seção-5c-critérios-expandidos-de-dm" id="toc-seção-5c-critérios-expandidos-de-dm" class="nav-link" data-scroll-target="#seção-5c-critérios-expandidos-de-dm">Seção 5C — Critérios Expandidos de DM</a></li>
  <li><a href="#seção-5d-consolidação-has-e-dm" id="toc-seção-5d-consolidação-has-e-dm" class="nav-link" data-scroll-target="#seção-5d-consolidação-has-e-dm">Seção 5D — Consolidação HAS e DM</a></li>
  <li><a href="#seção-5e-progressão-glicêmica" id="toc-seção-5e-progressão-glicêmica" class="nav-link" data-scroll-target="#seção-5e-progressão-glicêmica">Seção 5E — Progressão Glicêmica</a></li>
  <li><a href="#seção-5f-progressão-de-pressão-arterial" id="toc-seção-5f-progressão-de-pressão-arterial" class="nav-link" data-scroll-target="#seção-5f-progressão-de-pressão-arterial">Seção 5F — Progressão de Pressão Arterial</a></li>
  <li><a href="#seção-5g-prescrições-de-medicamentos-cardiovasculares" id="toc-seção-5g-prescrições-de-medicamentos-cardiovasculares" class="nav-link" data-scroll-target="#seção-5g-prescrições-de-medicamentos-cardiovasculares">Seção 5G — Prescrições de Medicamentos Cardiovasculares</a></li>
  <li><a href="#seção-5h-exames-solicitados-e-exame-do-pé-diabético" id="toc-seção-5h-exames-solicitados-e-exame-do-pé-diabético" class="nav-link" data-scroll-target="#seção-5h-exames-solicitados-e-exame-do-pé-diabético">Seção 5H — Exames Solicitados e Exame do Pé Diabético</a></li>
  <li><a href="#seção-7-consolidação-central-com-egfr" id="toc-seção-7-consolidação-central-com-egfr" class="nav-link" data-scroll-target="#seção-7-consolidação-central-com-egfr">Seção 7 — Consolidação Central com eGFR</a></li>
  <li><a href="#seção-7a-morbidades-consolidadas" id="toc-seção-7a-morbidades-consolidadas" class="nav-link" data-scroll-target="#seção-7a-morbidades-consolidadas">Seção 7A — Morbidades Consolidadas</a></li>
  <li><a href="#seção-7b-multimorbidade" id="toc-seção-7b-multimorbidade" class="nav-link" data-scroll-target="#seção-7b-multimorbidade">Seção 7B — Multimorbidade</a></li>
  <li><a href="#seção-9-10-escore-de-framingham-e-risco-cardiovascular" id="toc-seção-9-10-escore-de-framingham-e-risco-cardiovascular" class="nav-link" data-scroll-target="#seção-9-10-escore-de-framingham-e-risco-cardiovascular">Seção 9-10 — Escore de Framingham e Risco Cardiovascular</a></li>
  <li><a href="#seção-11-índice-de-charlson-modificado" id="toc-seção-11-índice-de-charlson-modificado" class="nav-link" data-scroll-target="#seção-11-índice-de-charlson-modificado">Seção 11 — Índice de Charlson Modificado</a></li>
  <li><a href="#seção-acb-escore-de-carga-anticolinérgica" id="toc-seção-acb-escore-de-carga-anticolinérgica" class="nav-link" data-scroll-target="#seção-acb-escore-de-carga-anticolinérgica">Seção ACB — Escore de Carga Anticolinérgica</a></li>
  <li><a href="#seção-benchmark" id="toc-seção-benchmark" class="nav-link" data-scroll-target="#seção-benchmark">Seção Benchmark</a></li>
  </ul></li>
  <li><a href="#lacunas-de-cuidado" id="toc-lacunas-de-cuidado" class="nav-link" data-scroll-target="#lacunas-de-cuidado">Lacunas de Cuidado</a>
  <ul class="collapse">
  <li><a href="#cardiopatia-isquêmica-cat-2" id="toc-cardiopatia-isquêmica-cat-2" class="nav-link" data-scroll-target="#cardiopatia-isquêmica-cat-2">Cardiopatia Isquêmica (CAT 2)</a></li>
  <li><a href="#icc-e-uso-inadequado-cat-3" id="toc-icc-e-uso-inadequado-cat-3" class="nav-link" data-scroll-target="#icc-e-uso-inadequado-cat-3">ICC e Uso Inadequado (CAT 3)</a></li>
  <li><a href="#fibrilação-atrial-cat-4" id="toc-fibrilação-atrial-cat-4" class="nav-link" data-scroll-target="#fibrilação-atrial-cat-4">Fibrilação Atrial (CAT 4)</a></li>
  <li><a href="#diabetes-cat-6" id="toc-diabetes-cat-6" class="nav-link" data-scroll-target="#diabetes-cat-6">Diabetes (CAT 6)</a></li>
  <li><a href="#exames-laboratoriais" id="toc-exames-laboratoriais" class="nav-link" data-scroll-target="#exames-laboratoriais">Exames Laboratoriais</a></li>
  <li><a href="#controle-de-pa" id="toc-controle-de-pa" class="nav-link" data-scroll-target="#controle-de-pa">Controle de PA</a></li>
  <li><a href="#rastreio-de-diabetes" id="toc-rastreio-de-diabetes" class="nav-link" data-scroll-target="#rastreio-de-diabetes">Rastreio de Diabetes</a></li>
  <li><a href="#pé-diabético" id="toc-pé-diabético" class="nav-link" data-scroll-target="#pé-diabético">Pé Diabético</a></li>
  </ul></li>
  <li><a href="#contagem-de-consultas-e-padrão-de-cuidado" id="toc-contagem-de-consultas-e-padrão-de-cuidado" class="nav-link" data-scroll-target="#contagem-de-consultas-e-padrão-de-cuidado">Contagem de Consultas e Padrão de Cuidado</a></li>
  <li><a href="#flags-de-inequidade" id="toc-flags-de-inequidade" class="nav-link" data-scroll-target="#flags-de-inequidade">Flags de Inequidade</a></li>
  <li><a href="#referências-clínicas" id="toc-referências-clínicas" class="nav-link" data-scroll-target="#referências-clínicas">Referências Clínicas</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Documentação Técnica: MM_2026_novos_cadastros</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="visão-geral" class="level2">
<h2 class="anchored" data-anchor-id="visão-geral">Visão Geral</h2>
<section id="objetivo" class="level3">
<h3 class="anchored" data-anchor-id="objetivo">Objetivo</h3>
<p>A tabela <code>rj-sms-sandbox.sub_pav_us.MM_2026_novos_cadastros</code> é a <strong>tabela fato principal</strong> do Navegador Clínico de Multimorbidade da SMS-RJ. Consolida dados de múltiplas fontes em <strong>uma linha por paciente (CPF)</strong>, integrando:</p>
<ul>
<li>Dados demográficos e de cadastro na ESF</li>
<li>56+ morbidades identificadas por CID</li>
<li>Diagnósticos expandidos de HAS e DM (CID + medidas + medicamentos)</li>
<li>Classificação de tipo provável de DM (DM1 vs DM2)</li>
<li>Exames laboratoriais e medidas antropométricas</li>
<li>Cálculos de risco cardiovascular (Framingham + estratificação SBC)</li>
<li>Índice de Charlson modificado com polifarmácia</li>
<li><strong>Escore de Carga Anticolinérgica (ACB — Anticholinergic Cognitive Burden Scale)</strong></li>
<li>Histórico de controle de condições crônicas</li>
<li>Mais de 30 lacunas de cuidado identificadas</li>
</ul>
</section>
<section id="localização" class="level3">
<h3 class="anchored" data-anchor-id="localização">Localização</h3>
<pre><code>Projeto : rj-sms-sandbox
Dataset : sub_pav_us
Tabela  : MM_2026_novos_cadastros</code></pre>
</section>
<section id="granularidade" class="level3">
<h3 class="anchored" data-anchor-id="granularidade">Granularidade</h3>
<p><strong>1 linha por CPF</strong> — cada paciente aparece uma única vez na tabela final.</p>
</section>
<section id="tabelas-dependentes-rodar-antes" class="level3">
<h3 class="anchored" data-anchor-id="tabelas-dependentes-rodar-antes">Tabelas Dependentes (rodar antes)</h3>
<p>A query principal depende de três tabelas auxiliares que devem ser geradas previamente, nesta ordem:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 29%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Ordem</th>
<th>Tabela</th>
<th>Finalidade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>sub_pav_us.indicadores_vitacare_fix</code></td>
<td>Correções de peso, altura, IMC, PA, glicemia e HbA1c extraídos do Vitacare</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>sub_pav_us.PA_A1C_glic_cpf_fix</code></td>
<td>Medidas corrigidas de PA, glicemia e HbA1c por episódio (<code>id_hci</code>)</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>sub_pav_us.MM_mdes_agudos_e_classes</code></td>
<td>Medicamentos agudos e classificação por classe terapêutica</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>sub_pav_us.mantidos_alterados</code></td>
<td>Núcleo crônico por paciente com status de mudança</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>sub_pav_us.MM_mantidos_alterados_ultimas</code></td>
<td>Última prescrição crônica por paciente com flags de polifarmácia <strong>e escore ACB</strong></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Nota sobre ACB:</strong> A tabela <code>MM_mantidos_alterados_ultimas</code> (e sua versão <code>_longo</code>) já contêm os escores ACB calculados diretamente na pipeline de prescrições. A tabela fato consome esses escores via JOIN simples, sem recálculo.</p>
</blockquote>
<hr>
</section>
</section>
<section id="arquitetura-de-dados" class="level2">
<h2 class="anchored" data-anchor-id="arquitetura-de-dados">Arquitetura de Dados</h2>
<section id="fontes-de-origem" class="level3">
<h3 class="anchored" data-anchor-id="fontes-de-origem">Fontes de Origem</h3>
<pre><code>┌─────────────────────────────────────────────────────────────────────────────┐
│                           FONTES DE DADOS                                    │
├─────────────────────────────────────────────────────────────────────────────┤
│ • brutos_prontuario_vitacare_historico.hiv                                  │
│ • brutos_prontuario_vitacare_historico.acto                                 │
│ • saude_historico_clinico.episodio_assistencial                             │
│ • saude_historico_clinico.exame                                             │
│ • saude_historico_clinico.paciente                                          │
│ • brutos_cientificalab.solicitacoes / exames / resultados                   │
│ • brutos_prontuario_vitacare.atendimento                                    │
│ • brutos_prontuario_vitacare.ficha_a                                        │
│ • sub_pav_us.indicadores_vitacare_fix  (tabela auxiliar pré-processada)     │
│ • sub_pav_us.PA_A1C_glic_cpf_fix       (tabela auxiliar pré-processada)     │
│ • sub_pav_us.MM_mantidos_alterados_ultimas (medicamentos crônicos + ACB)    │
└─────────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="fluxo-das-ctes" class="level3">
<h3 class="anchored" data-anchor-id="fluxo-das-ctes">Fluxo das CTEs</h3>
<pre><code>SEÇÃO 1: HIV/AIDS
  hiv_cpf_raw → hiv_cpf → exames_hiv_cpf_raw → exames_hiv_cpf_last → hiv_completo

SEÇÃO 2: Exames Laboratoriais
  exames_historico ─┐
  exames_cientifica ─┴→ todos_exames → exames_filtrados → exames_mais_recentes → exames_pivot

SEÇÃO 3: Demográficos
  ultima_ficha → dados_paciente

SEÇÃO 4: Antropométricos
  ultimas_medidas_antropometricas  (Vitacare + episodio_assistencial)

SEÇÃO 5: Morbidades
  morbidades_base → morbidades_por_cid

SEÇÃO 5B: Critérios HAS
  todas_medidas_pa → criterios_has_medidas
                     criterios_has_medicamentos

SEÇÃO 5C: Critérios DM
  todas_medidas_glicemia → criterios_dm_medidas
                           criterios_dm_medicamentos
                           classificacao_tipo_dm        ← NOVO

SEÇÃO 5D: Consolidação HAS + DM
  has_dm_consolidado  (inclui provavel_dm1)             ← NOVO

SEÇÃO 5E: Progressão Glicêmica
  hba1c_progressao → progressao_glicemica
  historico_controle_glicemia → resumo_controle_glicemia_dias → resumo_controle_glicemia
  ultimas_medidas_glicemia

SEÇÃO 5F: Progressão PA
  todas_medidas_pa_completas → pa_progressao → progressao_pressao
  historico_controle_pa → resumo_controle_pa_dias → resumo_controle_pa
  ultimas_medidas_pa

SEÇÃO 5G: Prescrições
  ultimas_prescricoes_medicamentos

SEÇÃO 5H: Exames Solicitados / Pé Diabético
  exames_solicitados_365d
  exame_pe_diabetico

SEÇÃO 7: Consolidação Central
  dados_consolidados  (JOIN de todas as seções acima + eGFR + CKD)

SEÇÃO 7A: Morbidades Consolidadas
  dados_com_irc → dados_com_hiv → dados_com_dislipidemia

SEÇÃO 7B: Multimorbidade
  morbidades_array → dados_com_multimorbidade

SEÇÃO 9-10: Risco Cardiovascular
  pontuacao_framingham → risco_calculado → risco_cardiovascular_estratificado

SEÇÃO 11: Charlson
  charlson_componentes → charlson_final
    ↑ JOIN com MM_mantidos_alterados_ultimas
      (medicamentos crônicos + polifarmácia + ACB)      ← NOVO

SEÇÃO 12: Benchmark
  benchmark_consultas

SELECT FINAL: Lacunas de cuidado + flags de inequidade + alerta_acb + alerta_acb_idoso</code></pre>
<hr>
</section>
</section>
<section id="detalhamento-por-seção" class="level2">
<h2 class="anchored" data-anchor-id="detalhamento-por-seção">Detalhamento por Seção</h2>
<hr>
<section id="seção-1-identificação-de-hivaids" class="level3">
<h3 class="anchored" data-anchor-id="seção-1-identificação-de-hivaids">Seção 1 — Identificação de HIV/AIDS</h3>
<p><strong>CTEs:</strong> <code>hiv_cpf_raw</code>, <code>hiv_cpf</code>, <code>exames_hiv_cpf_raw</code>, <code>exames_hiv_cpf_last</code>, <code>hiv_completo</code></p>
<p><strong>Fontes:</strong> - <code>brutos_prontuario_vitacare_historico.hiv</code> - <code>brutos_prontuario_vitacare_historico.acto</code> - <code>saude_historico_clinico.episodio_assistencial</code></p>
<p><strong>O que faz:</strong></p>
<p>Identifica pacientes com HIV a partir de duas fontes complementares:</p>
<ol type="1">
<li><strong>Base especializada Vitacare HIV</strong>: prontuário histórico com campo <code>aids_doenca_atual_ano_1_teste</code> — o ano do diagnóstico é validado (≥1980, ≤ano atual) e convertido para DATE.</li>
<li><strong>Exames de CD4/CV no episódio assistencial</strong>: busca descrições de exames com os termos <code>cd4</code>, <code>cv</code> ou <code>carga viral</code> via REGEXP.</li>
</ol>
<p>A unicidade por CPF é garantida por <code>QUALIFY ROW_NUMBER() = 1</code>, priorizando o registro mais recente.</p>
<p><strong>Campos produzidos em <code>hiv_completo</code>:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Tipo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cpf</code></td>
<td>STRING</td>
<td>CPF do paciente</td>
</tr>
<tr class="even">
<td><code>data_diagnostico_hiv</code></td>
<td>DATE</td>
<td>Ano do diagnóstico convertido para 1° de janeiro do ano</td>
</tr>
<tr class="odd">
<td><code>data_ultimo_exame_hiv</code></td>
<td>DATE</td>
<td>Data do último exame de CD4/CV identificado</td>
</tr>
</tbody>
</table>
<p><strong>Uso clínico:</strong> Permite identificar pacientes HIV+ a partir de fonte especializada, complementando o CID B20–B24. Utilizado na consolidação <code>HIV</code> (menor data entre CID e base externa) e no cálculo de pontuação do Charlson.</p>
<hr>
</section>
<section id="seção-2-exames-laboratoriais" class="level3">
<h3 class="anchored" data-anchor-id="seção-2-exames-laboratoriais">Seção 2 — Exames Laboratoriais</h3>
<p><strong>CTEs:</strong> <code>exames_historico</code>, <code>exames_cientifica</code>, <code>todos_exames</code>, <code>exames_filtrados</code>, <code>exames_mais_recentes</code>, <code>exames_pivot</code></p>
<p><strong>Fontes:</strong> - <code>saude_historico_clinico.exame</code> (histórico clínico) - <code>brutos_cientificalab.solicitacoes</code>, <code>brutos_cientificalab.exames</code>, <code>brutos_cientificalab.resultados</code> (Científica Lab)</p>
<p><strong>Exames capturados:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Código</th>
<th>Exame</th>
<th>Filtro de plausibilidade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>CRE</code></td>
<td>Creatinina</td>
<td>0,2–15 mg/dL com unidade <code>mg/dL</code></td>
</tr>
<tr class="even">
<td><code>COL</code></td>
<td>Colesterol total</td>
<td>50–600 mg/dL</td>
</tr>
<tr class="odd">
<td><code>HDL</code></td>
<td>HDL colesterol</td>
<td>10–150 mg/dL</td>
</tr>
<tr class="even">
<td><code>LDL</code></td>
<td>LDL colesterol</td>
<td>20–400 mg/dL</td>
</tr>
<tr class="odd">
<td><code>TRI</code></td>
<td>Triglicerídeos</td>
<td>20–1000 mg/dL</td>
</tr>
<tr class="even">
<td><code>GLI</code> / <code>GLU</code></td>
<td>Glicemia</td>
<td>30–500 mg/dL</td>
</tr>
<tr class="odd">
<td><code>HGL</code></td>
<td>HbA1c</td>
<td>3–20% com unidade <code>%</code></td>
</tr>
</tbody>
</table>
<p><strong>O que faz:</strong></p>
<p>As duas fontes são unidas via <code>UNION ALL</code>. Após filtros de plausibilidade clínica, seleciona o resultado <strong>mais recente</strong> por CPF e por tipo de exame (<code>QUALIFY ROW_NUMBER() = 1</code> ordenado por <code>data_exame DESC</code>). O pivot final produz uma linha por CPF com todos os valores e suas respectivas datas.</p>
<p><strong>Campos produzidos em <code>exames_pivot</code>:</strong></p>
<p>Valores: <code>creatinina</code>, <code>colesterol_total</code>, <code>hdl</code>, <code>ldl</code>, <code>triglicerides</code>, <code>glicemia</code>, <code>hba1c</code></p>
<p>Datas: <code>data_creatinina</code>, <code>data_colesterol</code>, <code>data_hdl</code>, <code>data_ldl</code>, <code>data_glicemia</code>, <code>data_hba1c</code></p>
<p>Indicadores: <code>dias_desde_ultimo_exame</code>, <code>dias_desde_ultima_glicemia</code></p>
<p><strong>Uso clínico:</strong> Base para cálculo de eGFR, estratificação de dislipidemia (ATP III), controle glicêmico, Framingham e lacunas de exames laboratoriais.</p>
<hr>
</section>
<section id="seção-3-dados-demográficos-e-de-cadastro" class="level3">
<h3 class="anchored" data-anchor-id="seção-3-dados-demográficos-e-de-cadastro">Seção 3 — Dados Demográficos e de Cadastro</h3>
<p><strong>CTEs:</strong> <code>ultima_ficha</code>, <code>dados_paciente</code></p>
<p><strong>Fontes:</strong> - <code>brutos_prontuario_vitacare.ficha_a</code> - <code>saude_historico_clinico.paciente</code></p>
<p><strong>Critérios de inclusão (filtros em <code>ultima_ficha</code>):</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cadastro_permanente <span class="op">=</span> <span class="kw">TRUE</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> (situacao_usuario <span class="op">=</span> <span class="st">'Ativo'</span> <span class="kw">OR</span> situacao_usuario <span class="kw">IS</span> <span class="kw">NULL</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> cpf <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> obito <span class="op">=</span> <span class="kw">FALSE</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> <span class="kw">NOT</span> REGEXP_CONTAINS(<span class="fu">UPPER</span>(equipe_nome), r<span class="st">'ESB'</span>)  <span class="co">-- exclui equipe de saúde bucal</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> ine_equipe <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>O registro mais recente por CPF é selecionado via <code>QUALIFY ROW_NUMBER() OVER (PARTITION BY cpf ORDER BY data_atualizacao_cadastro DESC) = 1</code>.</p>
<p><strong>Campos produzidos (grupos):</strong></p>
<ul>
<li><strong>Identificação:</strong> <code>cpf</code>, <code>nome</code>, <code>genero</code>, <code>data_nascimento</code>, <code>idade</code>, <code>raca</code></li>
<li><strong>Cadastro ESF:</strong> <code>id_ine_cadastro</code>, <code>nome_esf_cadastro</code>, <code>id_cnes_cadastro</code>, <code>nome_clinica_cadastro</code>, <code>nome_medico_esf_cadastro</code>, <code>nome_enfermeiro_esf_cadastro</code>, <code>area_programatica_cadastro</code></li>
<li><strong>Determinantes sociais:</strong> <code>escolaridade</code>, <code>renda_familiar</code>, <code>situacao_profissional</code>, <code>ocupacao</code>, <code>vulnerabilidade_social</code>, <code>em_situacao_de_rua</code>, <code>possui_plano_saude</code>, <code>familia_beneficiaria_cfc</code>, <code>familia_beneficiaria_auxilio_brasil</code></li>
<li><strong>Território:</strong> <code>bairro</code>, <code>logradouro</code>, <code>microarea</code>, <code>municipio_residencia</code>, <code>estado_residencia</code></li>
<li><strong>Moradia e saneamento:</strong> <code>tipo_domicilio</code>, <code>abastecimento_agua</code>, <code>esgotamento_sanitario</code>, <code>destino_lixo</code>, <code>luz_eletrica</code></li>
<li><strong>Saúde autorreferida:</strong> <code>doencas_condicoes_ficha_a</code> (array concatenado em string)</li>
</ul>
<p><strong>Uso clínico:</strong> Base de toda a estratificação territorial e de equipe. Permite filtrar pacientes por AP, clínica e ESF no dashboard.</p>
<hr>
</section>
<section id="seção-4-medidas-antropométricas" class="level3">
<h3 class="anchored" data-anchor-id="seção-4-medidas-antropométricas">Seção 4 — Medidas Antropométricas</h3>
<p><strong>CTE:</strong> <code>ultimas_medidas_antropometricas</code></p>
<p><strong>Fontes:</strong> - <code>sub_pav_us.indicadores_vitacare_fix</code> (peso, altura e IMC já corrigidos) - <code>saude_historico_clinico.episodio_assistencial</code> (medidas brutas)</p>
<p><strong>O que faz:</strong></p>
<p>Une as duas fontes e seleciona a medida mais recente por CPF (independente da fonte), ordenando por <code>COALESCE(data_peso, data_altura) DESC</code>. Não há prioridade por fonte — vence a data mais recente.</p>
<p>Para registros do episódio assistencial, peso e altura são buscados separadamente usando <code>FIRST_VALUE(...) IGNORE NULLS</code>, pois podem estar em episódios diferentes.</p>
<p>Correções aplicadas na tabela <code>indicadores_vitacare_fix</code> (pré-processada): - Altura em cm convertida para metros (valores entre 50–250) - Peso validado (30–300 kg) - IMC recalculado após correções</p>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>peso</code></td>
<td>Peso em kg</td>
</tr>
<tr class="even">
<td><code>altura</code></td>
<td>Altura em metros</td>
</tr>
<tr class="odd">
<td><code>IMC</code></td>
<td>kg/m²</td>
</tr>
<tr class="even">
<td><code>obesidade_por_IMC</code></td>
<td>TRUE se IMC ≥ 30</td>
</tr>
<tr class="odd">
<td><code>data_peso</code></td>
<td>Data da aferição de peso</td>
</tr>
<tr class="even">
<td><code>data_altura</code></td>
<td>Data da aferição de altura</td>
</tr>
<tr class="odd">
<td><code>fonte</code></td>
<td><code>'vitacare'</code> ou <code>'episodio_assistencial'</code></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-5-morbidades-por-cid" class="level3">
<h3 class="anchored" data-anchor-id="seção-5-morbidades-por-cid">Seção 5 — Morbidades por CID</h3>
<p><strong>CTEs:</strong> <code>morbidades_base</code>, <code>morbidades_por_cid</code></p>
<p><strong>Fonte:</strong> <code>saude_historico_clinico.episodio_assistencial</code> (campo <code>condicoes[]</code>)</p>
<p><strong>O que faz:</strong></p>
<p>Desnormaliza o array de condições de cada episódio assistencial, extrai o CID e, por CPF, calcula a <strong>data mínima</strong> (<code>MIN(entrada_data)</code>) para cada grupo de morbidade usando <code>REGEXP_CONTAINS</code>. Isso representa a <strong>primeira data de diagnóstico registrada</strong> no sistema.</p>
<p>A unicidade por CPF é garantida por <code>QUALIFY ROW_NUMBER() OVER (PARTITION BY cpf ORDER BY cpf) = 1</code>.</p>
<p><strong>Morbidades catalogadas por grupo:</strong></p>
<section id="grupo-1-principais" class="level4">
<h4 class="anchored" data-anchor-id="grupo-1-principais">Grupo 1: Principais</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>HAS</code></td>
<td><code>I1[0-6]</code>, <code>O1[01]</code></td>
<td>Hipertensão arterial sistêmica</td>
</tr>
<tr class="even">
<td><code>DM</code></td>
<td><code>E1[0-4]</code>, <code>O24</code>, <code>H360</code>, <code>H280</code>, <code>G632</code>, <code>G590</code>, <code>G990</code>, <code>N083</code>, <code>M142</code></td>
<td>Diabetes mellitus (todos os tipos)</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-2-cardiovasculares" class="level4">
<h4 class="anchored" data-anchor-id="grupo-2-cardiovasculares">Grupo 2: Cardiovasculares</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>CI</code></td>
<td><code>I2[0-5]</code>, <code>Z95[15]</code></td>
<td>Cardiopatia isquêmica</td>
</tr>
<tr class="even">
<td><code>ICC</code></td>
<td><code>I110</code>, <code>I13[02]</code>, <code>I42[0-9]</code>, <code>I43</code>, <code>I50</code>, <code>I517</code>, <code>P290</code></td>
<td>Insuficiência cardíaca congestiva</td>
</tr>
<tr class="odd">
<td><code>stroke</code></td>
<td><code>I6</code>, <code>G4[56]</code>, <code>H340</code></td>
<td>AVC/Stroke</td>
</tr>
<tr class="even">
<td><code>arritmia</code></td>
<td><code>I44[1-3]</code>, <code>I45[69]</code>, <code>I4[7-9]</code>, <code>R00[018]</code>, <code>T821</code>, <code>Z45[05]</code>, <code>Z950</code></td>
<td>Fibrilação/Flutter e outras arritmias</td>
</tr>
<tr class="odd">
<td><code>valvular</code></td>
<td><code>A520</code>, <code>I0[5-9]</code>, <code>I34</code>, <code>I3[5-9]</code>, <code>Q23[0-3]</code>, <code>Z95[2-4]</code></td>
<td>Doença valvar</td>
</tr>
<tr class="even">
<td><code>circ_pulm</code></td>
<td><code>I2[6-8]</code></td>
<td>Circulação pulmonar</td>
</tr>
<tr class="odd">
<td><code>vascular_periferica</code></td>
<td><code>I7[01]</code>, <code>I73[189]</code>, <code>I77[12]</code>, <code>I79[02]</code>, <code>K55[189]</code>, <code>Z95[89]</code></td>
<td>Doença arterial periférica</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-3-neurológicas" class="level4">
<h4 class="anchored" data-anchor-id="grupo-3-neurológicas">Grupo 3: Neurológicas</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>epilepsy</code></td>
<td><code>G4[01]</code></td>
<td>Epilepsia</td>
</tr>
<tr class="even">
<td><code>parkinsonism</code></td>
<td><code>G2[0-2]</code></td>
<td>Parkinsonismo</td>
</tr>
<tr class="odd">
<td><code>multiple_sclerosis</code></td>
<td><code>G35</code></td>
<td>Esclerose múltipla</td>
</tr>
<tr class="even">
<td><code>neuro</code></td>
<td><code>G1[0-3]</code>, <code>G25[45]</code>, <code>G31[012]</code>, <code>G3[2367]</code>, <code>G93[14]</code>, <code>R470</code>, <code>R56</code></td>
<td>Outras neurológicas</td>
</tr>
<tr class="odd">
<td><code>dementia</code></td>
<td><code>F0[0-35]</code>, <code>G30</code></td>
<td>Demência e Alzheimer</td>
</tr>
<tr class="even">
<td><code>plegia</code></td>
<td><code>G041</code>, <code>G114</code>, <code>G80[12]</code>, <code>G8[1-3]</code></td>
<td>Hemiplegia/Paraplegia</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-4-psiquiátricas" class="level4">
<h4 class="anchored" data-anchor-id="grupo-4-psiquiátricas">Grupo 4: Psiquiátricas</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>psicoses</code></td>
<td><code>F2[0-9]</code>, <code>F31</code></td>
<td>Esquizofrenia e transtornos psicóticos</td>
</tr>
<tr class="even">
<td><code>depre_ansiedade</code></td>
<td><code>F3[2-49]</code>, <code>F4[01]</code></td>
<td>Depressão e ansiedade</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-5-pulmonares" class="level4">
<h4 class="anchored" data-anchor-id="grupo-5-pulmonares">Grupo 5: Pulmonares</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>COPD</code></td>
<td><code>I27[89]</code>, <code>J4[0-4]</code>, <code>J47</code>, <code>J6[0-7]</code>, <code>J684</code>, <code>J70[13]</code></td>
<td>DPOC</td>
</tr>
<tr class="even">
<td><code>asthma</code></td>
<td><code>J4[56]</code></td>
<td>Asma</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-6-neoplasias" class="level4">
<h4 class="anchored" data-anchor-id="grupo-6-neoplasias">Grupo 6: Neoplasias</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>neoplasia_mama</code></td>
<td><code>C50</code></td>
<td>Ca de mama</td>
</tr>
<tr class="even">
<td><code>neoplasia_colo_uterino</code></td>
<td><code>C53</code></td>
<td>Ca de colo uterino</td>
</tr>
<tr class="odd">
<td><code>neoplasia_feminina_estrita</code></td>
<td><code>C5[1-28]</code></td>
<td>Neoplasias exclusivas femininas</td>
</tr>
<tr class="even">
<td><code>neoplasia_masculina_estrita</code></td>
<td><code>C6[0-3]</code></td>
<td>Neoplasias exclusivas masculinas</td>
</tr>
<tr class="odd">
<td><code>leukemia</code></td>
<td><code>C9[1-5]</code></td>
<td>Leucemia</td>
</tr>
<tr class="even">
<td><code>lymphoma</code></td>
<td><code>C8[1-6]</code>, <code>C96</code></td>
<td>Linfoma</td>
</tr>
<tr class="odd">
<td><code>metastasis</code></td>
<td><code>C7[7-9]</code>, <code>C80</code></td>
<td>Metástase / Ca disseminado</td>
</tr>
<tr class="even">
<td><code>neoplasia_ambos_os_sexos</code></td>
<td><code>C[0-4][0-9]</code>, <code>C[567][0-9]</code> (exceto específicos)</td>
<td>Outros cânceres</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-7-renais-e-metabólicas" class="level4">
<h4 class="anchored" data-anchor-id="grupo-7-renais-e-metabólicas">Grupo 7: Renais e Metabólicas</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>IRC_por_CID</code></td>
<td><code>I120</code>, <code>I131</code>, <code>N03[2-7]</code>, <code>N05[2-7]</code>, <code>N1[89]</code>, <code>N250</code>, <code>Z49[0-2]</code>, <code>Z940</code>, <code>Z992</code></td>
<td>IRC por CID (antes de unificar com eGFR)</td>
</tr>
<tr class="even">
<td><code>dislipidemia_por_CID</code></td>
<td><code>E78</code></td>
<td>Dislipidemia por CID</td>
</tr>
<tr class="odd">
<td><code>obesidade</code></td>
<td><code>E66</code></td>
<td>Obesidade por CID</td>
</tr>
<tr class="even">
<td><code>tireoide</code></td>
<td><code>E0[0-3]</code>, <code>E05</code>, <code>E06</code>, <code>E890</code></td>
<td>Doenças da tireoide</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-8-hematológicas" class="level4">
<h4 class="anchored" data-anchor-id="grupo-8-hematológicas">Grupo 8: Hematológicas</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>coagulo</code></td>
<td><code>D6[5-9]</code></td>
<td>Coagulopatias</td>
</tr>
<tr class="even">
<td><code>anemias</code></td>
<td><code>D5[0-3]</code></td>
<td>Anemias</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-9-reumatológicas" class="level4">
<h4 class="anchored" data-anchor-id="grupo-9-reumatológicas">Grupo 9: Reumatológicas</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>reumato</code></td>
<td><code>L93</code>, <code>L94[013]</code>, <code>M0[5-68]</code>, <code>M12[03]</code>, <code>M3[0-5]</code>, <code>M4[5-6]</code></td>
<td>Doenças reumatológicas</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-10-uso-de-substâncias" class="level4">
<h4 class="anchored" data-anchor-id="grupo-10-uso-de-substâncias">Grupo 10: Uso de Substâncias</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>alcool</code></td>
<td><code>F10</code>, <code>E52</code>, <code>G621</code>, <code>I426</code>, <code>K292</code>, <code>K70</code>, <code>T51</code>, <code>Z502</code>, <code>Z714</code>, <code>Z721</code></td>
<td>Transtorno por álcool</td>
</tr>
<tr class="even">
<td><code>drogas</code></td>
<td><code>F1[1-9]</code>, <code>Z715</code>, <code>Z722</code></td>
<td>Transtorno por drogas</td>
</tr>
<tr class="odd">
<td><code>tabaco</code></td>
<td><code>F17</code>, <code>Z716</code></td>
<td>Tabagismo</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-11-gastrointestinais" class="level4">
<h4 class="anchored" data-anchor-id="grupo-11-gastrointestinais">Grupo 11: Gastrointestinais</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>peptic</code></td>
<td><code>K2[5-8]</code></td>
<td>Úlcera péptica</td>
</tr>
<tr class="even">
<td><code>liver</code></td>
<td><code>B18</code>, <code>I8[56]</code>, <code>I982</code>, <code>K70</code>, <code>K71[1357]</code>, <code>K72[19]</code>, <code>K7[3-6]</code>, <code>Z944</code></td>
<td>Hepatopatia crônica</td>
</tr>
<tr class="odd">
<td><code>diverticular_disease</code></td>
<td><code>K57</code></td>
<td>Doença diverticular</td>
</tr>
<tr class="even">
<td><code>ibd</code></td>
<td><code>K5[01]</code></td>
<td>DII (Crohn/Retocolite)</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-12-infecciosas" class="level4">
<h4 class="anchored" data-anchor-id="grupo-12-infecciosas">Grupo 12: Infecciosas</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>SIDA</code></td>
<td><code>B2[0-4]</code>, <code>Z21</code>, <code>R75</code>, <code>O987</code>, <code>P352</code></td>
<td>HIV/AIDS por CID</td>
</tr>
</tbody>
</table>
</section>
<section id="grupo-13-outras" class="level4">
<h4 class="anchored" data-anchor-id="grupo-13-outras">Grupo 13: Outras</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>CIDs</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>desnutricao</code></td>
<td><code>E4[0-36]</code></td>
<td>Desnutrição</td>
</tr>
<tr class="even">
<td><code>retardo_mental</code></td>
<td><code>F7[0-9]</code></td>
<td>Deficiência intelectual</td>
</tr>
<tr class="odd">
<td><code>olhos</code></td>
<td><code>H18</code>, <code>H201</code>, <code>H2[56]</code>, <code>H33</code>, <code>H360</code>, <code>H4[026]</code>, <code>H46</code>, <code>H540</code></td>
<td>Doenças oculares</td>
</tr>
<tr class="even">
<td><code>ouvidos</code></td>
<td><code>H9[01]</code></td>
<td>Perda auditiva</td>
</tr>
<tr class="odd">
<td><code>ma_formacoes</code></td>
<td><code>Q0[0-7]</code>, <code>Q3[5-7]</code>, <code>Q6[0-2]</code>, <code>Q8[01]</code>, <code>Q9[0-9]</code></td>
<td>Malformações congênitas</td>
</tr>
<tr class="even">
<td><code>pele</code></td>
<td><code>L1[0-49]</code>, <code>L20</code>, <code>L4[013]</code>, <code>L80</code>, <code>L89</code>, <code>L90</code>, <code>L990</code>, <code>Q85[01]</code></td>
<td>Doenças cutâneas</td>
</tr>
<tr class="odd">
<td><code>painful_condition</code></td>
<td><code>R52[12]</code>, <code>M79[27]</code>, <code>G89[034]</code></td>
<td>Dor crônica</td>
</tr>
<tr class="even">
<td><code>prostate_disorder</code></td>
<td><code>N4[0-2]</code></td>
<td>Distúrbio de próstata</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="seção-5b-critérios-expandidos-de-has" class="level3">
<h3 class="anchored" data-anchor-id="seção-5b-critérios-expandidos-de-has">Seção 5B — Critérios Expandidos de HAS</h3>
<p><strong>CTEs:</strong> <code>todas_medidas_pa</code>, <code>criterios_has_medidas</code>, <code>criterios_has_medicamentos</code></p>
<p><strong>O que faz:</strong></p>
<p>Complementa o diagnóstico de HAS por CID com dois critérios adicionais baseados em evidências clínicas:</p>
<p><strong>Por medidas (via <code>PA_A1C_glic_cpf_fix</code>):</strong></p>
<ul>
<li><strong>Medida crítica única:</strong> PAS ≥ 180 ou PAD ≥ 110 — uma medida já define HAS</li>
<li><strong>Duas medidas repetidas:</strong> PAS entre 140–179 ou PAD entre 90–109, em pelo menos 2 episódios distintos. A data retornada é a da <strong>segunda</strong> medida alterada (<code>ARRAY_AGG(...)[SAFE_OFFSET(1)]</code>)</li>
</ul>
<p><strong>Por medicamentos (via <code>episodio_assistencial.prescricoes[]</code>):</strong></p>
<p>Identifica a <strong>primeira prescrição</strong> dos seguintes anti-hipertensivos:</p>
<pre><code>HIDROCLOROTIAZIDA | CLORTALIDONA | INDAPAMIDA | CAPTOPRIL | ENALAPRIL |
LISINOPRIL | RAMIPRIL | PERINDOPRIL | BENAZEPRIL | LOSARTANA | VALSARTANA |
CANDESARTANA | IRBESARTANA | OLMESARTANA | TELMISARTANA | ANLODIPINO |
NIFEDIPINO | FELODIPINO | VERAPAMIL | DILTIAZEM | ATENOLOL | PROPRANOLOL |
METOPROLOL | CARVEDILOL | BISOPROLOL | METILDOPA | CLONIDINA | HIDRALAZINA |
ALISQUIRENO</code></pre>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>has_por_medida_critica</code></td>
<td>Data da 1ª PA ≥ 180/110</td>
</tr>
<tr class="even">
<td><code>has_por_medidas_repetidas</code></td>
<td>Data da 2ª medida alterada (140–179/90–109)</td>
</tr>
<tr class="odd">
<td><code>has_por_medicamento</code></td>
<td>Data da 1ª prescrição de anti-hipertensivo</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-5c-critérios-expandidos-de-dm" class="level3">
<h3 class="anchored" data-anchor-id="seção-5c-critérios-expandidos-de-dm">Seção 5C — Critérios Expandidos de DM</h3>
<p><strong>CTEs:</strong> <code>todas_medidas_glicemia</code>, <code>criterios_dm_medidas</code>, <code>criterios_dm_medicamentos</code>, <code>classificacao_tipo_dm</code></p>
<p><strong>O que faz:</strong></p>
<p>Complementa o diagnóstico de DM por CID com critérios laboratoriais e farmacológicos.</p>
<p><strong>Por medidas (via <code>PA_A1C_glic_cpf_fix</code>):</strong></p>
<ul>
<li><strong>Diagnóstico direto:</strong> glicemia ≥ 126 mg/dL ou HbA1c ≥ 6,5% — uma medida já define DM</li>
<li><strong>Progressão pré-DM:</strong> glicemia entre 100–125 mg/dL ou HbA1c entre 5,7–6,4% em pelo menos 2 episódios distintos. A data retornada é a da <strong>segunda</strong> medida (<code>ARRAY_AGG(...)[SAFE_OFFSET(1)]</code>)</li>
<li><strong>Pré-DM:</strong> primeira medida na faixa pré-diabética (só preenchida quando DM = NULL)</li>
</ul>
<p><strong>Por medicamentos — hipoglicemiantes fortes:</strong></p>
<pre><code>GLICLAZIDA | GLIBENCLAMIDA | GLIMEPIRID | GLIPIZIDA | REPAGLINIDA |
NATEGLINIDA | PIOGLITAZONA | ROSIGLITAZONA | SITAGLIPTINA | VILDAGLIPTINA |
SAXAGLIPTINA | LINAGLIPTINA | EXENATIDA | DULAGLUTIDA | LIXISENATIDA |
TIRZEPATIDA | INSULINA | NPH | LISPRO | ASPARTE | GLULISINA | GLARGINA |
DETEMIR | DEGLUDECA</code></pre>
<blockquote class="blockquote">
<p><strong>Regra especial:</strong> Paciente com <strong>apenas metformina</strong> (sem nenhum hipoglicemiante forte) <strong>não</strong> é classificado como DM por medicamento — a metformina tem usos além do diabetes.</p>
</blockquote>
<p><strong>Por medicamentos — flag de insulina exclusiva (para classificação DM1):</strong></p>
<p>A CTE <code>classificacao_tipo_dm</code> verifica se o paciente usa <strong>insulina como único tratamento</strong>, sem nenhum antidiabético oral associado. Este flag alimenta a classificação <code>provavel_dm1</code>.</p>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>dm_por_exames</code></td>
<td>Data da 1ª glicemia ≥ 126 ou HbA1c ≥ 6,5%</td>
</tr>
<tr class="even">
<td><code>dm_por_progressao_pre_dm</code></td>
<td>Data da 2ª medida de pré-DM</td>
</tr>
<tr class="odd">
<td><code>pre_dm_por_exames</code></td>
<td>Data da 1ª medida de pré-DM (só se DM = NULL)</td>
</tr>
<tr class="even">
<td><code>dm_por_medicamento_forte</code></td>
<td>Data da 1ª prescrição de hipoglicemiante forte</td>
</tr>
<tr class="odd">
<td><code>tem_apenas_metformina</code></td>
<td>TRUE se metformina sem hipoglicemiante forte</td>
</tr>
<tr class="even">
<td><code>insulina_exclusiva</code></td>
<td>TRUE se insulina sem nenhum antidiabético oral</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-5d-consolidação-has-e-dm" class="level3">
<h3 class="anchored" data-anchor-id="seção-5d-consolidação-has-e-dm">Seção 5D — Consolidação HAS e DM</h3>
<p><strong>CTE:</strong> <code>has_dm_consolidado</code></p>
<p><strong>O que faz:</strong></p>
<p>Consolida todas as evidências de HAS e DM em campos únicos, tomando a <strong>menor data</strong> entre todas as fontes disponíveis.</p>
<p><strong>Lógica de consolidação do HAS:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>HAS <span class="op">=</span> <span class="fu">MIN</span>(has_por_cid, has_por_medida_critica, has_por_medidas_repetidas, has_por_medicamento)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>HAS_sem_CID <span class="op">=</span> <span class="kw">TRUE</span>  <span class="co">-- se HAS não é NULL mas has_por_cid é NULL</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Lógica de consolidação do DM:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>DM <span class="op">=</span> <span class="fu">MIN</span>(dm_por_cid, dm_por_exames, dm_por_progressao_pre_dm, dm_por_medicamento_forte)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>     <span class="co">-- exceto: se tem_apenas_metformina = TRUE e não há outras evidências → DM = NULL</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>pre_DM <span class="op">=</span> pre_dm_por_exames  <span class="co">-- SOMENTE se DM = NULL (exclusão mútua garantida)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>DM_sem_CID <span class="op">=</span> <span class="kw">TRUE</span>  <span class="co">-- se DM não é NULL mas dm_por_cid é NULL</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<blockquote class="blockquote">
<p><strong>Importante:</strong> <code>pre_DM</code> e <code>DM</code> são <strong>mutuamente exclusivos</strong>. Se o paciente tem diagnóstico de DM por qualquer critério, <code>pre_DM</code> é forçado a NULL.</p>
</blockquote>
<p><strong>Classificação provável de tipo de DM:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>provavel_dm1 <span class="op">=</span> <span class="kw">TRUE</span>  quando:</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- Critério A: CID E10 registrado em qualquer episódio</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- Critério B: insulina_exclusiva = TRUE</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>               <span class="kw">AND</span> diagnóstico de DM antes dos <span class="dv">35</span> anos</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>               (calculado como DATE_DIFF(DM, data_nascimento, <span class="dt">YEAR</span>) <span class="op">&lt;</span> <span class="dv">35</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<blockquote class="blockquote">
<p><strong>Nota clínica:</strong> O campo <code>provavel_dm1</code> é uma <strong>inferência baseada em dados administrativos</strong>, não um diagnóstico confirmado laboratorialmente (anticorpos GAD, peptídeo C). Deve ser interpretado como rastreio para identificar casos prioritários de revisão clínica.</p>
</blockquote>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Tipo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>HAS</code></td>
<td>DATE</td>
<td>Data mais precoce de diagnóstico de HAS</td>
</tr>
<tr class="even">
<td><code>has_por_cid</code></td>
<td>DATE</td>
<td>Data do primeiro CID de HAS</td>
</tr>
<tr class="odd">
<td><code>has_por_medida_critica</code></td>
<td>DATE</td>
<td>Data de PA ≥ 180/110</td>
</tr>
<tr class="even">
<td><code>has_por_medidas_repetidas</code></td>
<td>DATE</td>
<td>Data da 2ª medida alterada</td>
</tr>
<tr class="odd">
<td><code>has_por_medicamento</code></td>
<td>DATE</td>
<td>Data da 1ª prescrição anti-hipertensiva</td>
</tr>
<tr class="even">
<td><code>HAS_sem_CID</code></td>
<td>BOOL</td>
<td>HAS identificada sem CID correspondente</td>
</tr>
<tr class="odd">
<td><code>DM</code></td>
<td>DATE</td>
<td>Data mais precoce de diagnóstico de DM</td>
</tr>
<tr class="even">
<td><code>dm_por_cid</code></td>
<td>DATE</td>
<td>Data do primeiro CID de DM</td>
</tr>
<tr class="odd">
<td><code>dm_por_exames</code></td>
<td>DATE</td>
<td>Data da 1ª glicemia/HbA1c diagnóstica</td>
</tr>
<tr class="even">
<td><code>dm_por_progressao_pre_dm</code></td>
<td>DATE</td>
<td>Data da 2ª medida pré-diabética</td>
</tr>
<tr class="odd">
<td><code>dm_por_medicamento_forte</code></td>
<td>DATE</td>
<td>Data da 1ª prescrição de hipoglicemiante forte</td>
</tr>
<tr class="even">
<td><code>DM_sem_CID</code></td>
<td>BOOL</td>
<td>DM identificado sem CID correspondente</td>
</tr>
<tr class="odd">
<td><code>pre_DM</code></td>
<td>DATE</td>
<td>Data da 1ª evidência de pré-diabetes (NULL se DM presente)</td>
</tr>
<tr class="even">
<td><code>provavel_dm1</code></td>
<td>BOOL</td>
<td>Provável DM tipo 1 (CID E10 ou insulina exclusiva + diagnóstico &lt; 35 anos)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-5e-progressão-glicêmica" class="level3">
<h3 class="anchored" data-anchor-id="seção-5e-progressão-glicêmica">Seção 5E — Progressão Glicêmica</h3>
<p><strong>CTEs:</strong> <code>hba1c_progressao</code>, <code>progressao_glicemica</code>, <code>historico_controle_glicemia</code>, <code>resumo_controle_glicemia_dias</code>, <code>resumo_controle_glicemia</code>, <code>ultimas_medidas_glicemia</code></p>
<p><strong>O que faz:</strong></p>
<p>Calcula a tendência da HbA1c comparando a última medição com a anterior (via <code>LAG()</code>), e constrói um histórico temporal de controle glicêmico desde o diagnóstico de DM.</p>
<p><strong>Metas de HbA1c por idade:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Idade</th>
<th>Meta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 60 anos</td>
<td>≤ 7,0%</td>
</tr>
<tr class="even">
<td>≥ 60 anos</td>
<td>≤ 7,5%</td>
</tr>
</tbody>
</table>
<p><strong>Status de controle:</strong></p>
<ul>
<li>Para pacientes <strong>sem DM:</strong> <code>rastreio - normal</code>, <code>rastreio - pre_diabetes</code>, <code>rastreio - provável_diabetes</code></li>
<li>Para pacientes <strong>com DM:</strong> <code>dentro_da_meta</code>, <code>fora_da_meta</code>, <code>abaixo_da_meta</code> (idosos com HbA1c &lt; 6,0%), <code>sem_dados</code></li>
</ul>
<p><strong>Tendência (apenas para pacientes com DM fora da meta):</strong></p>
<ul>
<li><code>melhorando</code>: HbA1c atual &lt; anterior − 0,4%</li>
<li><code>piorando</code>: HbA1c atual &gt; anterior + 0,4%</li>
<li><code>estavel</code>: variação dentro de ±0,4%</li>
<li><code>sem_referencia_previa</code>: primeira medição registrada</li>
</ul>
<p><strong>Histórico temporal:</strong></p>
<p>O histórico calcula, desde a data do diagnóstico de DM até hoje, quantos dias o paciente passou em controle (<code>status = 'controlado'</code>) versus fora do controle. Os períodos entre medições são atribuídos ao status da medição anterior. O período entre o diagnóstico e a primeira HbA1c também é contabilizado.</p>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>hba1c_atual</code></td>
<td>Valor da última HbA1c</td>
</tr>
<tr class="even">
<td><code>data_hba1c_atual</code></td>
<td>Data da última HbA1c</td>
</tr>
<tr class="odd">
<td><code>hba1c_anterior</code></td>
<td>Valor da penúltima HbA1c</td>
</tr>
<tr class="even">
<td><code>data_hba1c_anterior</code></td>
<td>Data da penúltima HbA1c</td>
</tr>
<tr class="odd">
<td><code>dias_entre_hba1c</code></td>
<td>Intervalo entre as duas últimas medições</td>
</tr>
<tr class="even">
<td><code>meta_hba1c</code></td>
<td>Meta por idade (7,0% ou 7,5%)</td>
</tr>
<tr class="odd">
<td><code>status_controle_glicemico</code></td>
<td>Status atual de controle</td>
</tr>
<tr class="even">
<td><code>tendencia_hba1c</code></td>
<td>Tendência de evolução</td>
</tr>
<tr class="odd">
<td><code>dias_dm_controlado</code></td>
<td>Total de dias com DM controlado (histórico)</td>
</tr>
<tr class="even">
<td><code>dias_dm_descontrolado</code></td>
<td>Total de dias com DM fora da meta (histórico)</td>
</tr>
<tr class="odd">
<td><code>pct_dias_dm_controlado</code></td>
<td>% de tempo controlado (histórico total)</td>
</tr>
<tr class="even">
<td><code>dias_dm_controlado_365d</code></td>
<td>Dias controlado nos últimos 365 dias</td>
</tr>
<tr class="odd">
<td><code>pct_dias_dm_controlado_365d</code></td>
<td>% de tempo controlado nos últimos 365 dias</td>
</tr>
<tr class="even">
<td><code>dias_desde_ultima_hba1c</code></td>
<td>Dias desde a última HbA1c</td>
</tr>
<tr class="odd">
<td><code>ultimas_tres_glicemias</code></td>
<td>String com as 3 últimas glicemias (ex: “98 mg/dL; 112 mg/dL”)</td>
</tr>
<tr class="even">
<td><code>ultimas_tres_A1C</code></td>
<td>String com as 3 últimas HbA1c (ex: “7.2%; 8.1%”)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-5f-progressão-de-pressão-arterial" class="level3">
<h3 class="anchored" data-anchor-id="seção-5f-progressão-de-pressão-arterial">Seção 5F — Progressão de Pressão Arterial</h3>
<p><strong>CTEs:</strong> <code>todas_medidas_pa_completas</code>, <code>pa_progressao</code>, <code>progressao_pressao</code>, <code>historico_controle_pa</code>, <code>resumo_controle_pa_dias</code>, <code>resumo_controle_pa</code>, <code>ultimas_medidas_pa</code></p>
<p><strong>O que faz:</strong></p>
<p>Estrutura idêntica à seção de progressão glicêmica, aplicada à pressão arterial. Utiliza valores corrigidos de PA (COALESCE entre <code>PA_A1C_glic_cpf_fix</code> e medidas brutas do episódio assistencial).</p>
<p><strong>Metas de PAS por idade:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Idade</th>
<th>Meta PAS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 80 anos</td>
<td>&lt; 140 mmHg</td>
</tr>
<tr class="even">
<td>≥ 80 anos</td>
<td>&lt; 150 mmHg</td>
</tr>
</tbody>
</table>
<p><strong>Meta PAD:</strong> &lt; 90 mmHg (todas as idades)</p>
<p><strong>Tendência (apenas para pacientes com HAS fora da meta):</strong></p>
<ul>
<li><code>melhorando</code>: PAS atual &lt; anterior − 5 mmHg</li>
<li><code>piorando</code>: PAS atual &gt; anterior + 5 mmHg</li>
<li><code>estavel</code>: variação dentro de ±5 mmHg</li>
</ul>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pressao_sistolica</code></td>
<td>PAS da última medição</td>
</tr>
<tr class="even">
<td><code>pressao_diastolica</code></td>
<td>PAD da última medição</td>
</tr>
<tr class="odd">
<td><code>data_ultima_pa</code></td>
<td>Data da última medição</td>
</tr>
<tr class="even">
<td><code>dias_desde_ultima_pa</code></td>
<td>Dias desde a última PA</td>
</tr>
<tr class="odd">
<td><code>pas_anterior</code> / <code>pad_anterior</code></td>
<td>Penúltima medição</td>
</tr>
<tr class="even">
<td><code>variacao_pas</code> / <code>variacao_pad</code></td>
<td>Variação PAS/PAD atual − anterior</td>
</tr>
<tr class="odd">
<td><code>meta_pas</code> / <code>meta_pad</code></td>
<td>Metas por idade</td>
</tr>
<tr class="even">
<td><code>status_controle_pressorio</code></td>
<td>Status atual</td>
</tr>
<tr class="odd">
<td><code>tendencia_pa</code></td>
<td>Tendência de evolução</td>
</tr>
<tr class="even">
<td><code>dias_has_controlado</code></td>
<td>Total de dias com HAS controlada</td>
</tr>
<tr class="odd">
<td><code>pct_dias_has_controlado</code></td>
<td>% de tempo controlado (histórico total)</td>
</tr>
<tr class="even">
<td><code>pct_dias_has_controlado_365d</code></td>
<td>% de tempo controlado nos últimos 365 dias</td>
</tr>
<tr class="odd">
<td><code>ultimas_tres_PA</code></td>
<td>String com as 3 últimas PAs (ex: “130/85 mmHg; 142/90 mmHg”)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-5g-prescrições-de-medicamentos-cardiovasculares" class="level3">
<h3 class="anchored" data-anchor-id="seção-5g-prescrições-de-medicamentos-cardiovasculares">Seção 5G — Prescrições de Medicamentos Cardiovasculares</h3>
<p><strong>CTE:</strong> <code>ultimas_prescricoes_medicamentos</code></p>
<p><strong>Fonte:</strong> <code>saude_historico_clinico.episodio_assistencial</code> (campo <code>prescricoes[]</code>)</p>
<p><strong>O que faz:</strong></p>
<p>Para cada CPF, extrai a <strong>data mais recente</strong> de prescrição de 16 classes terapêuticas usando <code>REGEXP_CONTAINS</code> com nomes genéricos e comerciais em UPPERCASE.</p>
<p><strong>Classes monitoradas:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Medicamentos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>data_ultima_AAS</code></td>
<td>ASPIRINA, AAS, ACIDO ACETILSALICILICO, SOMALGIN, ECASIL</td>
</tr>
<tr class="even">
<td><code>data_ultima_anticoag</code></td>
<td>VARFARINA, WARFARIN, RIVAROXABAN, APIXABAN, DABIGATRAN, EDOXABAN</td>
</tr>
<tr class="odd">
<td><code>data_ultima_estatina_alta</code></td>
<td>ATORVASTATINA 40–80mg, ROSUVASTATINA 20–40mg</td>
</tr>
<tr class="even">
<td><code>data_ultima_estatina_qualquer</code></td>
<td>ATORVASTATINA, ROSUVASTATINA, SINVASTATINA, PRAVASTATINA, LOVASTATINA, FLUVASTATINA, PITAVASTATINA</td>
</tr>
<tr class="odd">
<td><code>data_ultima_SGLT2</code></td>
<td>DAPAGLIFLOZINA, EMPAGLIFLOZINA, CANAGLIFLOZINA, SOTAGLIFLOZINA</td>
</tr>
<tr class="even">
<td><code>data_ultima_BB</code></td>
<td>METOPROLOL SUCCINATO, CARVEDILOL, BISOPROLOL</td>
</tr>
<tr class="odd">
<td><code>data_ultima_IECA</code></td>
<td>CAPTOPRIL, ENALAPRIL, LISINOPRIL, RAMIPRIL, PERINDOPRIL, BENAZEPRIL</td>
</tr>
<tr class="even">
<td><code>data_ultima_BRA</code></td>
<td>LOSARTANA, VALSARTANA, CANDESARTANA, IRBESARTANA, OLMESARTANA, TELMISARTANA</td>
</tr>
<tr class="odd">
<td><code>data_ultima_INRA</code></td>
<td>SACUBITRIL, ENTRESTO</td>
</tr>
<tr class="even">
<td><code>data_ultima_diuretico_alca</code></td>
<td>FUROSEMIDA, BUMETANIDA, TORASEMIDA</td>
</tr>
<tr class="odd">
<td><code>data_ultima_ARM</code></td>
<td>ESPIRONOLACTONA, EPLERENONA</td>
</tr>
<tr class="even">
<td><code>data_ultima_BCC_nao_DHP</code></td>
<td>VERAPAMIL, DILTIAZEM</td>
</tr>
<tr class="odd">
<td><code>data_ultima_AINE</code></td>
<td>IBUPROFENO, DICLOFENACO, NAPROXENO, MELOXICAM, NIMESULIDA</td>
</tr>
<tr class="even">
<td><code>data_ultima_hidralazina</code></td>
<td>HIDRALAZINA</td>
</tr>
<tr class="odd">
<td><code>data_ultima_nitrato</code></td>
<td>ISOSSORBIDA, MONONITRATO, DINITRATO</td>
</tr>
<tr class="even">
<td><code>data_ultima_digoxina</code></td>
<td>DIGOXINA</td>
</tr>
</tbody>
</table>
<p><strong>Uso clínico:</strong> Base para cálculo das lacunas de cuidado cardiovascular. No SELECT final, cada data é acompanhada de <code>dias_desde_ultima_[classe]</code> calculado como <code>DATE_DIFF(CURRENT_DATE(), data, DAY)</code> com <code>COALESCE(..., 999999)</code> quando ausente.</p>
<hr>
</section>
<section id="seção-5h-exames-solicitados-e-exame-do-pé-diabético" class="level3">
<h3 class="anchored" data-anchor-id="seção-5h-exames-solicitados-e-exame-do-pé-diabético">Seção 5H — Exames Solicitados e Exame do Pé Diabético</h3>
<p><strong>CTEs:</strong> <code>exames_solicitados_365d</code>, <code>exame_pe_diabetico</code></p>
<p><strong>Fonte:</strong> <code>brutos_prontuario_vitacare.atendimento</code> (campos JSON <code>exames_solicitados</code> e <code>soap_plano_procedimentos_clinicos</code>)</p>
<p><strong>O que faz:</strong></p>
<p>Verifica, nos últimos 365 dias, se determinados exames foram <strong>solicitados</strong> (não necessariamente realizados) no Vitacare, usando <code>JSON_EXTRACT_SCALAR</code> sobre arrays JSON.</p>
<p><strong>Exames monitorados:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Regex de detecção</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>tem_creatinina_365d</code></td>
<td><code>CREATININA</code></td>
</tr>
<tr class="even">
<td><code>tem_colesterol_365d</code></td>
<td><code>COLESTEROL\|HDL\|LDL\|TRIGLICERID</code></td>
</tr>
<tr class="odd">
<td><code>tem_eas_365d</code></td>
<td><code>URINA\|CARACTERES\|SEDIMENTO\|EAS</code></td>
</tr>
<tr class="even">
<td><code>tem_ecg_365d</code></td>
<td><code>ELETROCARDIOGRAMA\|ECG</code></td>
</tr>
<tr class="odd">
<td><code>tem_hba1c_solicitado_365d</code></td>
<td><code>HEMOGLOBINA.*GLICO\|HBA1C</code></td>
</tr>
<tr class="even">
<td><code>tem_glicemia_365d</code></td>
<td><code>GLICOSE\|GLICEMIA</code></td>
</tr>
<tr class="odd">
<td><code>tem_microalbuminuria_365d</code></td>
<td><code>MICROALBUMIN</code></td>
</tr>
<tr class="even">
<td><code>tem_hemograma_365d</code></td>
<td><code>HEMOGRAMA\|ERITROGRAMA</code></td>
</tr>
</tbody>
</table>
<p><strong>Exame do pé diabético:</strong></p>
<p>Detecta o procedimento <code>EXAME.*PÉ.*DIABÉTICO</code> nos procedimentos clínicos do SOAP, com flags para 365 e 180 dias, data do último exame e dias desde o último.</p>
<hr>
</section>
<section id="seção-7-consolidação-central-com-egfr" class="level3">
<h3 class="anchored" data-anchor-id="seção-7-consolidação-central-com-egfr">Seção 7 — Consolidação Central com eGFR</h3>
<p><strong>CTE:</strong> <code>dados_consolidados</code></p>
<p><strong>O que faz:</strong></p>
<p>Realiza o <code>LEFT JOIN</code> de todas as seções anteriores em torno da tabela <code>dados_paciente</code> (base do cadastro). Além de consolidar os campos, calcula o <strong>eGFR</strong> usando a fórmula <strong>CKD-EPI 2021</strong> e o <strong>estadiamento CKD</strong> (G1 a G5).</p>
<p><strong>Fórmula CKD-EPI 2021:</strong></p>
<pre><code>eGFR = 142 × min(Cr/κ, 1)^α × max(Cr/κ, 1)^(−1.200) × 0.9938^idade × [1.012 se feminino]

Onde:
  κ = 0.7 (feminino) ou 0.9 (masculino)
  α = −0.241 (feminino) ou −0.302 (masculino)</code></pre>
<p><strong>Estadiamento CKD (KDIGO):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estágio</th>
<th>eGFR</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>G1</td>
<td>≥ 90</td>
<td>Normal ou alta</td>
</tr>
<tr class="even">
<td>G2</td>
<td>60–89</td>
<td>Levemente diminuída</td>
</tr>
<tr class="odd">
<td>G3</td>
<td>30–59</td>
<td>Moderadamente diminuída</td>
</tr>
<tr class="even">
<td>G4</td>
<td>15–29</td>
<td>Severamente diminuída</td>
</tr>
<tr class="odd">
<td>G5</td>
<td>&lt; 15</td>
<td>Falência renal</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-7a-morbidades-consolidadas" class="level3">
<h3 class="anchored" data-anchor-id="seção-7a-morbidades-consolidadas">Seção 7A — Morbidades Consolidadas</h3>
<p><strong>CTEs:</strong> <code>dados_com_irc</code>, <code>dados_com_hiv</code>, <code>dados_com_dislipidemia</code></p>
<p><strong>O que faz:</strong></p>
<p>Aplica três camadas de consolidação sequenciais via <code>SELECT *</code> + campo adicional:</p>
<p><strong>IRC unificada:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>IRC <span class="op">=</span> IRC_por_CID  <span class="co">-- se CID presente</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    OU data_creatinina  <span class="co">-- se ckd_stage ∈ {G3, G4, G5} e sem CID</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    OU <span class="kw">NULL</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>HIV unificado:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>HIV <span class="op">=</span> <span class="fu">LEAST</span>(SIDA, data_diagnostico_hiv)  <span class="co">-- menor data entre CID e base externa</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Dislipidemia (CID + critérios ATP III):</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dislipidemia <span class="op">=</span> <span class="fu">LEAST</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    dislipidemia_por_CID,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    data_colesterol  se CT ≥ <span class="dv">200</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    data_ldl         se LDL ≥ <span class="dv">130</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    data_hdl         se HDL <span class="op">&lt;</span> <span class="dv">40</span> (M) ou <span class="op">&lt;</span> <span class="dv">50</span> (F)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Classificações ATP III produzidas:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Categorias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>classificacao_colesterol_total</code></td>
<td>Desejável / Limítrofe alto / Alto</td>
</tr>
<tr class="even">
<td><code>classificacao_ldl</code></td>
<td>Ótimo / Acima do ótimo / Limítrofe alto / Alto / Muito alto</td>
</tr>
<tr class="odd">
<td><code>classificacao_hdl</code></td>
<td>Baixo / Normal / Desejável (protetor)</td>
</tr>
<tr class="even">
<td><code>classificacao_triglicerides</code></td>
<td>Normal / Limítrofe alto / Alto / Muito alto</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-7b-multimorbidade" class="level3">
<h3 class="anchored" data-anchor-id="seção-7b-multimorbidade">Seção 7B — Multimorbidade</h3>
<p><strong>CTEs:</strong> <code>morbidades_array</code>, <code>dados_com_multimorbidade</code></p>
<p><strong>O que faz:</strong></p>
<p>Desnormaliza todas as <strong>datas de diagnóstico</strong> (das morbidades consolidadas) em um array, conta as distintas e extrai a 2ª data como marco do início da multimorbidade.</p>
<p><strong>Morbidades incluídas no array:</strong></p>
<p>HAS, DM, CI, ICC, stroke, arritmia, valvular, circ_pulm, vascular_periferica, epilepsy, parkinsonism, multiple_sclerosis, neuro, dementia, plegia, psicoses, COPD, asthma, neoplasia_mama, neoplasia_colo_uterino, neoplasia_feminina_estrita, neoplasia_masculina_estrita, leukemia, lymphoma, metastasis, neoplasia_ambos_os_sexos, IRC, dislipidemia, obesidade, tireoide, coagulo, reumato, alcool, drogas, liver, diverticular_disease, ibd, HIV.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> <code>ARRAY_AGG(DISTINCT data)</code> garante que duas morbidades diagnosticadas na mesma data sejam contadas como uma única entrada.</p>
</blockquote>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>total_morbidades</code></td>
<td>Número de condições crônicas distintas</td>
</tr>
<tr class="even">
<td><code>multimorbidade</code></td>
<td>Data da 2ª morbidade (início da multimorbidade)</td>
</tr>
<tr class="odd">
<td><code>eh_multimorbido</code></td>
<td>TRUE se <code>total_morbidades</code> ≥ 2</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-9-10-escore-de-framingham-e-risco-cardiovascular" class="level3">
<h3 class="anchored" data-anchor-id="seção-9-10-escore-de-framingham-e-risco-cardiovascular">Seção 9-10 — Escore de Framingham e Risco Cardiovascular</h3>
<p><strong>CTEs:</strong> <code>pontuacao_framingham</code>, <code>risco_calculado</code>, <code>risco_cardiovascular_estratificado</code></p>
<p><strong>O que faz:</strong></p>
<p>Calcula o risco cardiovascular em 10 anos usando a versão do <strong>Escore de Framingham por pontos</strong> com tabelas distintas para homens e mulheres, seguido de reclassificação conforme a <strong>Diretriz Brasileira de Prevenção Cardiovascular (SBC)</strong>.</p>
<p><strong>Variáveis pontuadas:</strong></p>
<ul>
<li>Idade (faixas com pontos negativos para mulheres jovens)</li>
<li>Colesterol total</li>
<li>HDL colesterol</li>
<li>Pressão sistólica (pontuação diferente com e sem tratamento de HAS)</li>
<li>Diabetes mellitus (+2 homens, +4 mulheres)</li>
<li>Tabagismo (+2 ambos os sexos)</li>
</ul>
<p><strong>Reclassificação SBC:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Situação</th>
<th>Categoria final</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CI, Stroke ou Doença Arterial Periférica presentes</td>
<td>MUITO ALTO</td>
</tr>
<tr class="even">
<td>IRC, eGFR &lt; 60 ou LDL ≥ 190 mg/dL</td>
<td>ALTO</td>
</tr>
<tr class="odd">
<td>Framingham &gt; 20% (H) ou &gt; 10% (F)</td>
<td>ALTO</td>
</tr>
<tr class="even">
<td>DM + Framingham &lt; 20%</td>
<td>INTERMEDIÁRIO</td>
</tr>
<tr class="odd">
<td>Framingham 5–20% (H) ou 5–10% (F)</td>
<td>INTERMEDIÁRIO</td>
</tr>
<tr class="even">
<td>Framingham &lt; 5%</td>
<td>BAIXO</td>
</tr>
</tbody>
</table>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pontos_totais</code></td>
<td>Soma dos pontos de Framingham</td>
</tr>
<tr class="even">
<td><code>risco_framingham_calculado</code></td>
<td>% de risco em 10 anos (valor numérico)</td>
</tr>
<tr class="odd">
<td><code>percentual_risco_final</code></td>
<td>% formatado ou “&gt;20%”, “&gt;30%” após reclassificação</td>
</tr>
<tr class="even">
<td><code>categoria_risco_final</code> / <code>risco_cardiovascular</code></td>
<td>BAIXO / INTERMEDIÁRIO / ALTO / MUITO ALTO</td>
</tr>
<tr class="odd">
<td><code>motivo_reclassificacao</code></td>
<td>Texto descritivo do motivo (se houve reclassificação)</td>
</tr>
<tr class="even">
<td><code>tipo_estratificacao</code></td>
<td><code>usar_framingham</code> / <code>reclassificado_muito_alto</code> / etc</td>
</tr>
<tr class="odd">
<td><code>variaveis_usadas_calculo</code></td>
<td>String com variáveis disponíveis no cálculo</td>
</tr>
<tr class="even">
<td><code>variaveis_ausentes_calculo</code></td>
<td>String com variáveis faltantes</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="seção-11-índice-de-charlson-modificado" class="level3">
<h3 class="anchored" data-anchor-id="seção-11-índice-de-charlson-modificado">Seção 11 — Índice de Charlson Modificado</h3>
<p><strong>CTEs:</strong> <code>charlson_componentes</code>, <code>charlson_final</code></p>
<p><strong>O que faz:</strong></p>
<p>Calcula um índice de complexidade clínica baseado no <strong>Charlson Comorbidity Index</strong> com três modificações:</p>
<ol type="1">
<li>Adição de morbidades do <strong>Elixhauser</strong> não presentes no Charlson original (arritmia, psicoses)</li>
<li>Inclusão de <strong>polifarmácia</strong> como dimensão própria</li>
<li>Revisão dos pesos de algumas morbidades para melhor adequação ao contexto de atenção primária</li>
</ol>
<p><strong>Pesos por morbidade:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th>Peso</th>
<th>Morbidades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>HAS, arritmia, valvular, circ_pulm, vascular_periferica, epilepsy, neuro, psicoses, COPD, DM, coagulo, reumato, alcool, drogas, tabaco, ibd</td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td>CI, ICC, stroke, parkinsonism, multiple_sclerosis, dementia, plegia, HIV, desnutricao, neoplasias sólidas, leukemia, lymphoma</td>
</tr>
<tr class="odd">
<td><strong>3</strong></td>
<td>IRC, liver</td>
</tr>
<tr class="even">
<td><strong>6</strong></td>
<td>metastasis</td>
</tr>
</tbody>
</table>
<p><strong>Pontos por idade:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Faixa</th>
<th>Pontos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 40 anos</td>
<td>0</td>
</tr>
<tr class="even">
<td>40–49 anos</td>
<td>1</td>
</tr>
<tr class="odd">
<td>50–59 anos</td>
<td>2</td>
</tr>
<tr class="even">
<td>60–69 anos</td>
<td>3</td>
</tr>
<tr class="odd">
<td>70–79 anos</td>
<td>4</td>
</tr>
<tr class="even">
<td>≥ 80 anos</td>
<td>5</td>
</tr>
</tbody>
</table>
<p><strong>Pontos por polifarmácia</strong> (fonte: <code>MM_mantidos_alterados_ultimas</code>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Medicamentos crônicos</th>
<th>Pontos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0–4</td>
<td>0</td>
</tr>
<tr class="even">
<td>5–9 (polifarmácia)</td>
<td>1</td>
</tr>
<tr class="odd">
<td>≥ 10 (hiperpolifarmácia)</td>
<td>2</td>
</tr>
</tbody>
</table>
<p><strong>Score total = pontos morbidades + pontos idade + pontos polifarmácia</strong></p>
<p><strong>Categorias de risco:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Categoria</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>≤ 2</td>
<td>Baixo</td>
</tr>
<tr class="even">
<td>3–6</td>
<td>Moderado</td>
</tr>
<tr class="odd">
<td>7–9</td>
<td>Alto</td>
</tr>
<tr class="even">
<td>≥ 10</td>
<td>Muito Alto</td>
</tr>
</tbody>
</table>
<p><strong>Campos produzidos:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>charlson_pontos_morbidades</code></td>
<td>Pontos das comorbidades</td>
</tr>
<tr class="even">
<td><code>charlson_pontos_idade</code></td>
<td>Pontos da faixa etária</td>
</tr>
<tr class="odd">
<td><code>charlson_pontos_polifarmacia</code></td>
<td>Pontos da polifarmácia</td>
</tr>
<tr class="even">
<td><code>charlson_score</code></td>
<td>Score total</td>
</tr>
<tr class="odd">
<td><code>charlson_categoria</code></td>
<td>Baixo / Moderado / Alto / Muito Alto</td>
</tr>
<tr class="even">
<td><code>charlson_mediana</code></td>
<td>Mediana do grupo (faixa etária ×5 anos × sexo) via <code>PERCENTILE_CONT</code></td>
</tr>
<tr class="odd">
<td><code>total_medicamentos_cronicos</code></td>
<td>Contagem de medicamentos crônicos ativos</td>
</tr>
<tr class="even">
<td><code>nucleo_cronico_atual</code></td>
<td>Lista normalizada dos medicamentos crônicos</td>
</tr>
<tr class="odd">
<td><code>data_ultima_prescricao_cronica</code></td>
<td>Data da última prescrição crônica</td>
</tr>
<tr class="even">
<td><code>polifarmacia</code></td>
<td>TRUE se 5–9 medicamentos</td>
</tr>
<tr class="odd">
<td><code>hiperpolifarmacia</code></td>
<td>TRUE se ≥ 10 medicamentos</td>
</tr>
</tbody>
</table>
<p>Os campos de medicamentos crônicos e ACB chegam via JOIN com <code>MM_mantidos_alterados_ultimas</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> `rj<span class="op">-</span>sms<span class="op">-</span>sandbox.sub_pav_us.MM_mantidos_alterados_ultimas` med</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="kw">ON</span> rc.cpf <span class="op">=</span> med.cpf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="seção-acb-escore-de-carga-anticolinérgica" class="level3">
<h3 class="anchored" data-anchor-id="seção-acb-escore-de-carga-anticolinérgica">Seção ACB — Escore de Carga Anticolinérgica</h3>
<p><strong>Fonte:</strong> <code>sub_pav_us.MM_mantidos_alterados_ultimas</code> (campos <code>acb_*</code>)</p>
<section id="o-que-é-o-acb" class="level4">
<h4 class="anchored" data-anchor-id="o-que-é-o-acb">O que é o ACB</h4>
<p>A <strong>Anticholinergic Cognitive Burden (ACB) Scale</strong> quantifica o efeito cumulativo do uso de medicamentos com atividade anticolinérgica. Medicamentos anticolinérgicos bloqueiam receptores muscarínicos, causando efeitos periféricos (boca seca, constipação, retenção urinária) e centrais (confusão, déficit de memória, delirium, risco aumentado de demência e mortalidade).</p>
<p><strong>Referência principal:</strong> Boustani M, Campbell N, Munger S, Maidment I, Fox C. Impact of anticholinergics on the aging brain: a review and practical application. <em>Aging Health</em>. 2008;4(3):311–320.</p>
</section>
<section id="pipeline-de-cálculo" class="level4">
<h4 class="anchored" data-anchor-id="pipeline-de-cálculo">Pipeline de Cálculo</h4>
<p>O escore ACB é calculado <strong>na pipeline de prescrições</strong>, não na tabela fato:</p>
<pre><code>brutos_prontuario_vitacare.atendimento  (prescricoes[])
        ↓
acb_dict  (dicionário inline — scores 1, 2, 3)
        ↓
dados_com_acb  (JOIN por primeira palavra do nome limpo do medicamento)
        ↓
medicamentos_por_prescricao  (agregação por prescrição/consulta)
        ↓
MM_mantidos_alterados_longo   ← scores + médias móveis por prescrição
MM_mantidos_alterados_ultimas ← scores da última prescrição por CPF
        ↓
MM_2026_novos_cadastros  ← JOIN simples, sem recálculo</code></pre>
</section>
<section id="pontuação-individual-por-medicamento" class="level4">
<h4 class="anchored" data-anchor-id="pontuação-individual-por-medicamento">Pontuação Individual por Medicamento</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 44%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Score</th>
<th>Significado</th>
<th>Exemplos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>Possível efeito anticolinérgico em laboratório; sem evidência de efeito cognitivo clinicamente relevante</td>
<td>Metformina, Lorazepam, Digoxina, Omeprazol, Sertralina, Fluoxetina, Cetirizina, Clonazepam</td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td>Efeito anticolinérgico estabelecido, abaixo do limiar crítico</td>
<td>Tramadol, Pimozida, Trifluoperazina</td>
</tr>
<tr class="odd">
<td><strong>3</strong></td>
<td>Efeito anticolinérgico estabelecido e clinicamente relevante</td>
<td>Amitriptilina, Quetiapina, Olanzapina, Clozapina, Oxibutinina, Prometazina, Difenidramina, Ciclobenzaprina</td>
</tr>
</tbody>
</table>
</section>
<section id="ponto-de-corte-clínico" class="level4">
<h4 class="anchored" data-anchor-id="ponto-de-corte-clínico">Ponto de Corte Clínico</h4>
<p><strong>ACB total ≥ 3 é clinicamente relevante</strong> (Boustani et al., 2008). Acima desse limiar há associação comprovada com comprometimento cognitivo, aumento de internações e mortalidade.</p>
</section>
<section id="médias-móveis-e-tendência" class="level4">
<h4 class="anchored" data-anchor-id="médias-móveis-e-tendência">Médias Móveis e Tendência</h4>
<p>Calculadas com funções de janela na versão <code>_longo</code> (1 linha por prescrição):</p>
<ul>
<li><strong><code>media_movel_acb_3</code>:</strong> média do ACB nas últimas 3 prescrições crônicas (<code>ROWS BETWEEN 2 PRECEDING AND CURRENT ROW</code>)</li>
<li><strong><code>media_movel_acb_6</code>:</strong> média nas últimas 6 prescrições (<code>ROWS BETWEEN 5 PRECEDING AND CURRENT ROW</code>)</li>
<li><strong><code>tendencia_acb</code>:</strong> score atual − média das 3 prescrições anteriores. Valor positivo indica carga crescente; negativo, redução.</li>
</ul>
</section>
<section id="distribuição-observada-na-população-sms-rj-2026" class="level4">
<h4 class="anchored" data-anchor-id="distribuição-observada-na-população-sms-rj-2026">Distribuição Observada na População (SMS-RJ, 2026)</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Faixa ACB</th>
<th>N pacientes</th>
<th>%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 — sem carga</td>
<td>1.294.786</td>
<td>68,6%</td>
</tr>
<tr class="even">
<td>1 — possível efeito</td>
<td>386.087</td>
<td>20,5%</td>
</tr>
<tr class="odd">
<td>2 — efeito estabelecido</td>
<td>51.285</td>
<td>2,7%</td>
</tr>
<tr class="even">
<td>≥ 3 — clinicamente relevante</td>
<td>155.509</td>
<td>8,2%</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>155 mil pacientes (8,2%)</strong> apresentam carga anticolinérgica clinicamente relevante. Desses, parcela significativa tem polifarmácia associada (≥ 5 medicamentos), amplificando o risco cognitivo.</p>
</blockquote>
</section>
<section id="campos-produzidos" class="level4">
<h4 class="anchored" data-anchor-id="campos-produzidos">Campos Produzidos</h4>
<p><strong>Vindos de <code>MM_mantidos_alterados_ultimas</code> via JOIN:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Tipo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>acb_score_total</code></td>
<td>INTEGER</td>
<td>Soma dos scores ACB de todos os medicamentos da última prescrição</td>
</tr>
<tr class="even">
<td><code>acb_score_cronicos</code></td>
<td>INTEGER</td>
<td>ACB apenas dos medicamentos crônicos</td>
</tr>
<tr class="odd">
<td><code>acb_score_agudos</code></td>
<td>INTEGER</td>
<td>ACB apenas dos medicamentos agudos</td>
</tr>
<tr class="even">
<td><code>n_meds_acb_positivo</code></td>
<td>INTEGER</td>
<td>Número de medicamentos com ACB &gt; 0</td>
</tr>
<tr class="odd">
<td><code>n_meds_acb_alto</code></td>
<td>INTEGER</td>
<td>Número de medicamentos com ACB = 3</td>
</tr>
<tr class="even">
<td><code>acb_score_maximo</code></td>
<td>INTEGER</td>
<td>Score do medicamento mais anticolinérgico</td>
</tr>
<tr class="odd">
<td><code>medicamentos_acb_positivos</code></td>
<td>STRING</td>
<td>Lista com scores (ex: <code>Quetiapina(3); Lorazepam(1)</code>)</td>
</tr>
<tr class="even">
<td><code>media_movel_acb_3</code></td>
<td>FLOAT</td>
<td>Média do ACB nas últimas 3 prescrições crônicas</td>
</tr>
<tr class="odd">
<td><code>media_movel_acb_6</code></td>
<td>FLOAT</td>
<td>Média do ACB nas últimas 6 prescrições crônicas</td>
</tr>
<tr class="even">
<td><code>tendencia_acb</code></td>
<td>FLOAT</td>
<td>Score atual − média das 3 anteriores (positivo = aumentando)</td>
</tr>
<tr class="odd">
<td><code>categoria_acb</code></td>
<td>STRING</td>
<td><code>BAIXO</code> (0) / <code>MODERADO</code> (1–2) / <code>ALTO</code> (3–5) / <code>MUITO_ALTO</code> (≥ 6)</td>
</tr>
</tbody>
</table>
<p><strong>Derivados no SELECT final da tabela fato:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 17%">
<col style="width: 25%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Tipo</th>
<th>Critério</th>
<th>Uso clínico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>alerta_acb</code></td>
<td>BOOLEAN</td>
<td><code>acb_score_total</code> ≥ 3</td>
<td>Ponto de corte clínico de Boustani 2008</td>
</tr>
<tr class="even">
<td><code>alerta_acb_idoso</code></td>
<td>BOOLEAN</td>
<td><code>idade</code> ≥ 65 E <code>acb_score_total</code> ≥ 3</td>
<td>Risco aumentado de demência e quedas em idosos</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Nota clínica sobre <code>alerta_acb_idoso</code>:</strong> Idosos têm menor reserva colinérgica central, tornando-os mais vulneráveis a cargas anticolinérgicas mesmo em doses que não causariam efeitos em adultos jovens. O critério ≥ 65 anos alinha-se com os critérios de Beers e STOPP/START para prescrição potencialmente inapropriada em idosos.</p>
</blockquote>
<hr>
</section>
</section>
<section id="seção-benchmark" class="level3">
<h3 class="anchored" data-anchor-id="seção-benchmark">Seção Benchmark</h3>
<p><strong>CTE:</strong> <code>benchmark_consultas</code></p>
<p><strong>O que faz:</strong></p>
<p>Calcula estatísticas de referência (P25, P50, P75, média) de consultas e intervalo entre consultas para grupos de pacientes com perfil similar, definidos por:</p>
<ul>
<li>Faixa etária: <code>&lt;40</code>, <code>40-59</code>, <code>60-79</code>, <code>80+</code></li>
<li>Sexo</li>
<li>Risco Charlson: <code>baixo</code> (≤2), <code>moderado</code> (3–6), <code>alto</code> (≥7)</li>
</ul>
<p><strong>Uso clínico:</strong> Permite comparar o padrão de acesso de cada paciente com seus pares, identificando <code>alto_risco_baixo_acesso</code>, <code>baixo_risco_alto_acesso</code> e <code>alto_risco_intervalo_longo</code> como flags de inequidade em saúde.</p>
<hr>
</section>
</section>
<section id="lacunas-de-cuidado" class="level2">
<h2 class="anchored" data-anchor-id="lacunas-de-cuidado">Lacunas de Cuidado</h2>
<p>As lacunas são calculadas diretamente no SELECT final como campos BOOL (<code>TRUE</code> = lacuna identificada).</p>
<section id="cardiopatia-isquêmica-cat-2" class="level3">
<h3 class="anchored" data-anchor-id="cardiopatia-isquêmica-cat-2">Cardiopatia Isquêmica (CAT 2)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_CI_sem_AAS</code></td>
<td>CI presente + sem AAS nem anticoagulante nos últimos 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_CI_sem_estatina_alta</code></td>
<td>CI presente + sem estatina de alta intensidade em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_CI_sem_estatina_qualquer</code></td>
<td>CI presente + sem nenhuma estatina em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_CI_ICC_sem_BB</code></td>
<td>CI + ICC + sem betabloqueador em 365 dias</td>
</tr>
</tbody>
</table>
</section>
<section id="icc-e-uso-inadequado-cat-3" class="level3">
<h3 class="anchored" data-anchor-id="icc-e-uso-inadequado-cat-3">ICC e Uso Inadequado (CAT 3)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_ICC_sem_SGLT2</code></td>
<td>ICC + sem glifozina em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_ICC_sem_IECA_BRA</code></td>
<td>ICC + sem IECA nem BRA em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_ICC_sem_INRA</code></td>
<td>ICC + sem Entresto em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_IECA_BRA_concomitante</code></td>
<td>IECA + BRA prescritos simultaneamente nos últimos 180 dias (duplo bloqueio, contraindicado)</td>
</tr>
<tr class="odd">
<td><code>lacuna_diur_alca_sem_ICC</code></td>
<td>Diurético de alça prescrito nos últimos 180 dias sem diagnóstico de ICC</td>
</tr>
<tr class="even">
<td><code>lacuna_ICC_sem_ARM</code></td>
<td>ICC + sem espironolactona/eplerenona em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_ICC_INRA_IECA_concomitante</code></td>
<td>ICC + INRA + IECA simultâneos nos últimos 180 dias (perigoso)</td>
</tr>
<tr class="even">
<td><code>lacuna_ICC_uso_BCC_nao_DHP</code></td>
<td>ICC + verapamil/diltiazem nos últimos 180 dias (contraindicado)</td>
</tr>
<tr class="odd">
<td><code>lacuna_ICC_uso_AINE</code></td>
<td>ICC + AINE nos últimos 180 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_IRC_sem_SGLT2</code></td>
<td>IRC + sem glifozina em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_DM_complicado_sem_SGLT2</code></td>
<td>DM + (ICC ou IRC ou CI) + sem glifozina em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_IRC_sem_iECA_ou_BRA</code></td>
<td>IRC + sem IECA nem BRA em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_ICC_sem_SRAA_e_sem_hidralazina_nitrato</code></td>
<td>ICC sem nenhuma vasodilatação neurohormonal (IECA/BRA/INRA/hidralazina/nitrato) em 365 dias</td>
</tr>
</tbody>
</table>
</section>
<section id="fibrilação-atrial-cat-4" class="level3">
<h3 class="anchored" data-anchor-id="fibrilação-atrial-cat-4">Fibrilação Atrial (CAT 4)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_FA_sem_anticoagulacao</code></td>
<td>Arritmia + sem anticoagulante em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_FA_sem_controle_FC</code></td>
<td>Arritmia + sem BB nem digoxina em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_FA_ICC_sem_digoxina</code></td>
<td>Arritmia + ICC + sem digoxina em 365 dias</td>
</tr>
</tbody>
</table>
</section>
<section id="diabetes-cat-6" class="level3">
<h3 class="anchored" data-anchor-id="diabetes-cat-6">Diabetes (CAT 6)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_DM_sem_HbA1c_recente</code></td>
<td>DM + sem HbA1c nos últimos 180 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_DM_descontrolado</code></td>
<td>DM + HbA1c recente &gt; meta por idade</td>
</tr>
<tr class="odd">
<td><code>lacuna_DM_hba1c_nao_solicitado</code></td>
<td>DM + sem solicitação de HbA1c em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_DM_microalbuminuria_nao_solicitado</code></td>
<td>DM + sem microalbuminúria em 365 dias</td>
</tr>
</tbody>
</table>
</section>
<section id="exames-laboratoriais" class="level3">
<h3 class="anchored" data-anchor-id="exames-laboratoriais">Exames Laboratoriais</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_creatinina_HAS_DM</code></td>
<td>HAS ou DM + sem creatinina solicitada em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_colesterol_HAS_DM</code></td>
<td>HAS ou DM + sem perfil lipídico em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_eas_HAS_DM</code></td>
<td>HAS ou DM + sem EAS em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_ecg_HAS_DM</code></td>
<td>HAS ou DM + sem ECG em 365 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_IMC_HAS_DM</code></td>
<td>HAS ou DM + sem peso ou altura registrados</td>
</tr>
</tbody>
</table>
</section>
<section id="controle-de-pa" class="level3">
<h3 class="anchored" data-anchor-id="controle-de-pa">Controle de PA</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_rastreio_PA_adulto</code></td>
<td>≥ 18 anos + sem HAS + sem PA em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_PA_hipertenso_180d</code></td>
<td>HAS + sem PA nos últimos 180 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_HAS_descontrolado_menor80</code></td>
<td>HAS + &lt; 80 anos + PA recente ≥ 140/90</td>
</tr>
<tr class="even">
<td><code>lacuna_HAS_descontrolado_80mais</code></td>
<td>HAS + ≥ 80 anos + PA recente ≥ 150/90</td>
</tr>
<tr class="odd">
<td><code>lacuna_DM_HAS_PA_descontrolada</code></td>
<td>DM + HAS + PA recente &gt; 135/80 (meta mais restrita)</td>
</tr>
</tbody>
</table>
</section>
<section id="rastreio-de-diabetes" class="level3">
<h3 class="anchored" data-anchor-id="rastreio-de-diabetes">Rastreio de Diabetes</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_rastreio_DM_hipertenso</code></td>
<td>HAS + sem DM + sem glicemia ou HbA1c em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_rastreio_DM_45mais</code></td>
<td>≥ 45 anos + sem DM + sem glicemia ou HbA1c em 3 anos (1095 dias)</td>
</tr>
</tbody>
</table>
</section>
<section id="pé-diabético" class="level3">
<h3 class="anchored" data-anchor-id="pé-diabético">Pé Diabético</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lacuna_DM_sem_exame_pe_365d</code></td>
<td>DM + sem exame do pé em 365 dias</td>
</tr>
<tr class="even">
<td><code>lacuna_DM_sem_exame_pe_180d</code></td>
<td>DM + sem exame do pé em 180 dias</td>
</tr>
<tr class="odd">
<td><code>lacuna_DM_nunca_teve_exame_pe</code></td>
<td>DM há &gt; 1 ano + nenhum exame do pé registrado</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="contagem-de-consultas-e-padrão-de-cuidado" class="level2">
<h2 class="anchored" data-anchor-id="contagem-de-consultas-e-padrão-de-cuidado">Contagem de Consultas e Padrão de Cuidado</h2>
<p><strong>CTEs:</strong> <code>contagem_consultas_detalhada</code>, <code>intervalos_consultas_raw</code>, <code>intervalos_consultas</code>, <code>contagem_consultas</code></p>
<p><strong>Janelas temporais disponíveis:</strong> histórico total, últimos 365 dias, 180 dias, 90 dias.</p>
<p><strong>Tipos de profissional monitorados:</strong></p>
<ul>
<li>Médico ESF / Clínico</li>
<li>Outros médicos</li>
<li>Enfermeiro</li>
<li>ACS (Agente Comunitário de Saúde)</li>
<li>Técnico de Enfermagem ESF</li>
</ul>
<p><strong>Tipos de estabelecimento monitorados:</strong></p>
<ul>
<li>Clínica da Família (CF)</li>
<li>Centro Municipal de Saúde (CMS)</li>
<li>UPA / CER / Hospital (urgência)</li>
<li>Hospital (separado)</li>
<li>CAPS</li>
<li>Maternidade</li>
<li>Policlínica</li>
</ul>
<p><strong>Indicadores de longitudinalidade:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>baixa_longitudinalidade</code></td>
<td>&gt; 50% das consultas médicas fora da unidade de cadastro</td>
</tr>
<tr class="even">
<td><code>usuario_frequente_urgencia</code></td>
<td>≥ 3 visitas a urgência em 365 dias</td>
</tr>
<tr class="odd">
<td><code>meses_com_consulta_12m</code></td>
<td>Meses distintos com pelo menos 1 consulta nos últimos 12 meses</td>
</tr>
<tr class="even">
<td><code>regularidade_acompanhamento</code></td>
<td><code>regular</code> (≥6 meses) / <code>irregular</code> (3–5) / <code>esporadico</code> (1–2) / <code>sem_acompanhamento</code></td>
</tr>
<tr class="odd">
<td><code>perfil_cuidado_365d</code></td>
<td><code>medico_centrado</code> / <code>enfermagem_centrado</code> / <code>compartilhado</code> / <code>sem_consultas</code></td>
</tr>
<tr class="even">
<td><code>intervalo_mediano_dias</code></td>
<td>Mediana dos intervalos entre consultas nos últimos 365 dias</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="flags-de-inequidade" class="level2">
<h2 class="anchored" data-anchor-id="flags-de-inequidade">Flags de Inequidade</h2>
<p>Calculadas no SELECT final por comparação com o benchmark do grupo:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>alto_risco_baixo_acesso</code></td>
<td>Charlson ≥ 7 + consultas abaixo do P25 do grupo</td>
</tr>
<tr class="even">
<td><code>baixo_risco_alto_acesso</code></td>
<td>Charlson ≤ 2 + consultas acima do P75 do grupo</td>
</tr>
<tr class="odd">
<td><code>alto_risco_intervalo_longo</code></td>
<td>Charlson ≥ 7 + intervalo mediano acima do P75 do grupo</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="referências-clínicas" class="level2">
<h2 class="anchored" data-anchor-id="referências-clínicas">Referências Clínicas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th>Área</th>
<th>Referência</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Risco cardiovascular</td>
<td>Escore de Framingham por pontos (Wilson et al., 1998)</td>
</tr>
<tr class="even">
<td>Estratificação de risco</td>
<td>Diretriz Brasileira de Prevenção Cardiovascular — SBC 2019</td>
</tr>
<tr class="odd">
<td>Função renal</td>
<td>Fórmula CKD-EPI 2021 (Inker et al., NEJM 2021)</td>
</tr>
<tr class="even">
<td>Estadiamento renal</td>
<td>KDIGO 2012 Clinical Practice Guideline</td>
</tr>
<tr class="odd">
<td>Dislipidemia</td>
<td>Critérios ATP III (National Cholesterol Education Program)</td>
</tr>
<tr class="even">
<td>Comorbidades</td>
<td>Charlson Comorbidity Index (Charlson et al., 1987; van Walraven 2011)</td>
</tr>
<tr class="odd">
<td>Metas glicêmicas</td>
<td>Diretrizes SBD 2023</td>
</tr>
<tr class="even">
<td>Metas pressóricas</td>
<td>7ª Diretriz Brasileira de HAS — SBC/SBH 2016</td>
</tr>
<tr class="odd">
<td><strong>Carga anticolinérgica</strong></td>
<td><strong>Boustani M, Campbell N, Munger S, Maidment I, Fox C. Impact of anticholinergics on the aging brain: a review and practical application. <em>Aging Health</em>. 2008;4(3):311–320.</strong></td>
</tr>
<tr class="even">
<td><strong>ACB — impacto cognitivo</strong></td>
<td><strong>Campbell N, Boustani M, Limbil T, et al.&nbsp;The cognitive impact of anticholinergics: a clinical review. <em>Clin Interv Aging</em>. 2009;4:225–233.</strong></td>
</tr>
<tr class="odd">
<td><strong>ACB — ponto de corte ≥ 3</strong></td>
<td><strong>Campbell NL, Perkins AJ, Bradt P, et al.&nbsp;Association of Anticholinergic Burden with Cognitive Impairment and Health Care Utilization Among a Diverse Ambulatory Older Adult Population. <em>Pharmacotherapy</em>. 2016;36(11):1123–1131.</strong></td>
</tr>
</tbody>
</table>
<hr>
<p><em>Documentação gerada em março de 2026 — Projeto Navegador Clínico de Multimorbidade / SMS-RJ</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./pente_fino_HAS.html" class="pagination-link" aria-label="Pente Fino HAS">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Pente Fino HAS</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./script_MM.html" class="pagination-link" aria-label="Tabela MM_2026_novos_cadastros_stopp_start">
        <span class="nav-page-text">Tabela MM_2026_novos_cadastros_stopp_start</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>